#! /bin/sh
# NOTE: A common pattern is to specify "-" (stdout) as out-file,
#  so there must be NO log printouts to stdout!

dir=$(dirname $0); dir=$(readlink -f $dir)
tmp=/tmp/$USER/xcluster_$$
die() {
	echo "ERROR: $*" >&2
	rm -rf $tmp
	exit 1
}
log() {
	echo "INFO: $*" >&2
}
findf() {
	f=$ARCHIVE/$1
	test -r $f || f=$HOME/Downloads/$1
	test -r $f
}

test -n "$1" || die "No out-file"

mkdir -p $tmp
cp -R $dir/default/* $tmp

mkdir -p $tmp/bin
$dir/podman.sh install $tmp/bin || die "Dependency installation failed"
$XCLUSTER cplib --dest=$tmp $tmp/bin/conmon
$XCLUSTER cplib --dest=$tmp $tmp/bin/crun
$XCLUSTER cplib --dest=$tmp $tmp/bin/aardvark-dns
$XCLUSTER cplib --dest=$tmp $tmp/bin/netavark
$XCLUSTER cplib --dest=$tmp $tmp/bin/podman

mkdir -p $tmp/opt/cni/bin
x=$($XCLUSTER ovld cni-plugins)/cni-plugins.sh
$x install --dest=$tmp/opt/cni/bin || die

test -n "$SRIOV_DIR" || \
	SRIOV_DIR=$GOPATH/src/github.com/k8snetworkplumbingwg/sriov-cni
f=$SRIOV_DIR/build/sriov
test -x $f && cp $f $tmp/opt/cni/bin
echo "Installed sriov CNI"

cd $tmp
tar cf "$1" *
cd - > /dev/null
rm -rf $tmp
