#! /bin/sh
# NOTE: A common pattern is to specify "-" (stdout) as out-file,
#  so there must be NO log printouts to stdout!

dir=$(dirname $0); dir=$(readlink -f $dir)
tmp=/tmp/$USER/xcluster_$$
die() {
	echo "ERROR: $*" >&2
	rm -rf $tmp
	exit 1
}
log() {
	echo "INFO: $*" >&2
}

test -n "$1" || die "No out-file"

mkdir -p $tmp
cp -R $dir/default/* $tmp

$XCLUSTER install_prog --dest=$tmp envsubst
$dir/dhcp.sh isc_dir > /dev/null || die isc_dir
d=$($dir/dhcp.sh isc_dir)
x=$d/dhcpd
cp $x $tmp/bin
$dir/dhcp.sh radvd_dir > /dev/null || die radvd_dir
d=$($dir/dhcp.sh radvd_dir)
for x in radvd radvdump; do
	cp $d/$x $tmp/bin
done

test -n "$NFQLBDIR" || NFQLBDIR=$HOME/tmp/nfqlb
x=$NFQLBDIR/bin/ipu
test -x $x || die "Not executable [$x]"
cp $x $tmp/bin

cd $tmp
tar cf "$1" *
cd - > /dev/null
rm -rf $tmp
