apiVersion: v1
kind: Service
metadata:
  name: xcbase
spec:
  selector:
    app: xcbase
  ports:
  - protocol: TCP
    port: 80
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: xcbase-deployment
spec:
  selector:
    matchLabels:
      app: xcbase
  replicas: 4
  template:
    metadata:
      labels:
        app: xcbase
    spec:
      containers:
      - name: xcbase
        image: library/xcbase:v1.0
