apiVersion: apps/v1
kind: Deployment
metadata:
  name: xcluster-base
spec:
  selector:
    matchLabels:
      app: xcluster-base
  replicas: 4
  template:
    metadata:
      labels:
        app: xcluster-base
    spec:
      containers:
      - name: xcluster-base
        image: registry.nordix.org/cloud-native/xcluster-base:latest
        securityContext:
          privileged: true
        env:
        - name: TZ
          value: "NZST-12:00:00NZDT-13:00:00,M10.1.0,M3.3.0"
