apiVersion: v1
kind: Service
metadata:
  name: mconnect-cilium-ipv4
  labels:
    service.kubernetes.io/service-proxy-name: cilium 
spec:
  ipFamily: IPv4
  selector:
    app: mconnect
  ports:
  - port: 5001
  type: LoadBalancer
  loadBalancerIP: "10.0.0.0"
---
apiVersion: v1
kind: Service
metadata:
  name: mconnect-cilium-ipv6
  annotations:
    service.kubernetes.io/service-proxy-name: cilium 
spec:
  ipFamily: IPv6
  selector:
    app: mconnect
  ports:
  - port: 5001
  type: LoadBalancer
  loadBalancerIP: "1000::"
