#! /bin/sh

# Dpdk uses extended instructions. Don't know which so turn on all;
export __kvm_opt='-object rng-random,filename=/dev/urandom,id=rng0 -device virtio-rng-pci,rng=rng0,max-bytes=1024,period=80000 -cpu host'

eval $(./dpdk.sh env | grep __dpdk_src)
export __dpdk_src
PKG_CONFIG_PATH=$__dpdk_src/build/sys/usr/local/lib/x86_64-linux-gnu/pkgconfig
grep -qE 'VERSION_ID="18\.[0-9]+"' /etc/os-release \
  && PKG_CONFIG_PATH=$__dpdk_src/build/sys/usr/local/lib/x86_64-linux-gnu/pkgconfig
export PKG_CONFIG_PATH
unset __mem __mem201 __mem202 __mem203 __mem1
