#! /bin/sh
/bin/busybox echo "Alpine Xcluster starting..."
mkdir -p /proc /sys /tmp /dev/pts /dev/shm /var/log \
	/sbin /usr/bin /usr/sbin /dev/mqueue
mount -t sysfs sysfs /sys
mount -t proc procfs /proc
mdev -s

mkdir -p /run /var/log/dumps /var/tmp
ln -s /run /var/run

mount /tmp

echo /sbin/mdev > /proc/sys/kernel/hotplug

mount /dev/shm
mount /dev/pts
mount -o remount -w /
mdev -s
mount /dev/mqueue

# Get data from cdrom
test -b /dev/hdb && cddev=/dev/hdb
test -b /dev/vdb && cddev=/dev/vdb
if test -n "$cddev"; then
	mkdir -p /mnt
	if mount -t iso9660 $cddev /mnt > /dev/null 2>&1; then
		for n in $(find /mnt -name '*.tar' | sort); do
			EXTRACT_UNSAFE_SYMLINKS=1 tar -C / -xf $n
		done
		umount /mnt
	fi
fi

sysctl -p > /dev/null
depmod
ldconfig

rm -f /dev/console
mknod /dev/console c 5 1

#sed -i -e 's,console,tty0,' /etc/inittab
test -r /etc/init.d/init.hook && . /etc/init.d/init.hook
exec /sbin/init
