#! /bin/sh
# NOTE: A common pattern is to specify "-" (stdout) as out-file,
#  so there must be NO log printouts to stdout!

dir=$(dirname $0); dir=$(readlink -f $dir)
tmp=/tmp/$USER/xcluster_$$
die() {
	echo "ERROR: $*" >&2
	rm -rf $tmp
	exit 1
}
log() {
	echo "INFO: $*" >&2
}

test -n "$1" || die "No out-file"

# This ovl it intended to be used from other ovl's so only the
# essentials are in "default/", the rest is in "test/".
mkdir -p $tmp
cp -R $dir/default/* $tmp
cp $dir/multus-install.yaml $tmp/etc/kubernetes/multus

ar=$($dir/multus.sh archive)
eval $($dir/multus.sh env | grep __multus_ver=)
mkdir -p $tmp/opt/cni/bin
tar -C $tmp/opt/cni/bin --strip-components=1 -xf $ar multus-cni_${__multus_ver}_linux_amd64/multus-cni

mkdir -p $tmp/opt/cni/bin
x=$($XCLUSTER ovld cni-plugins)/cni-plugins.sh
$x install --dest=$tmp/opt/cni/bin || die

test -n "$WHEREABOUTS_DIR" || \
	WHEREABOUTS_DIR=$GOPATH/src/github.com/k8snetworkplumbingwg/whereabouts
test -n "$NODEANNOTATION_DIR" || \
	NODEANNOTATION_DIR=$GOPATH/src/github.com/Nordix/ipam-node-annotation
test -n "$SRIOV_DIR" || \
	SRIOV_DIR=$GOPATH/src/github.com/k8snetworkplumbingwg/sriov-cni

for f in $WHEREABOUTS_DIR/bin/whereabouts \
	$NODEANNOTATION_DIR/node-annotation \
	$SRIOV_DIR/build/sriov; do
	test -x $f && cp $f $tmp/opt/cni/bin
done

if test -d $WHEREABOUTS_DIR/doc/crds; then
	mkdir -p $tmp/etc/kubernetes
	cp -r $WHEREABOUTS_DIR/doc/crds $tmp/etc/kubernetes/whereabouts
fi

# Include test files if specified
if echo "$SETUP" | grep -qi test; then
	if echo "$SETUP" | grep -qi image; then
		# We will install with the "multus-installer" image so only
		# include the test program
		mkdir -p $tmp/bin
		cp $dir/test/bin/multus_test $tmp/bin
	else
		cp -R $dir/test/* $tmp
		mkdir -p $tmp/bin
		for n in multus-proxy multus-service-controller; do
			f=$GOPATH/bin/$n
			test -x $f && cp $f $tmp/bin
		done
	fi
fi

cd $tmp
tar cf "$1" *
cd - > /dev/null
rm -rf $tmp
