#! /bin/sh
# NOTE: A common pattern is to specify "-" (stdout) as out-file,
#  so there must be NO log printouts to stdout!

dir=$(dirname $0); dir=$(readlink -f $dir)
tmp=/tmp/$USER/xcluster_$$
die() {
	echo "ERROR: $*" >&2
	rm -rf $tmp
	exit 1
}
log() {
	echo "INFO: $*" >&2
}

test -n "$1" || die "No out-file"

mkdir -p $tmp
cp -R $dir/default/* $tmp

d=$GOPATH/src/github.com/lldpd/lldpd/build/sys/
cp -R $d/* $tmp || die "Please build lldpd first (./lldp.sh build_lldpd)"
$XCLUSTER cplib --dest=$tmp $tmp/sbin/lldp*

cd $tmp
tar cf "$1" *
cd - > /dev/null
rm -rf $tmp
