apiVersion: v1
kind: Service
metadata:
  name: mconnect-nfproxy
  labels:
    service.kubernetes.io/service-proxy-name: nfproxy
spec:
  selector:
    app: mconnect-daemonset
  ports:
  - port: 5001
  type: LoadBalancer

