apiVersion: v1
kind: Service
metadata:
  name: mconnect-nfproxy-ipv4
  labels:
    service.kubernetes.io/service-proxy-name: nfproxy
spec:
  ipFamily: IPv4
  selector:
    app: mconnect
  ports:
  - port: 5001
  type: LoadBalancer
  loadBalancerIP: "10.0.0.1"
---
apiVersion: v1
kind: Service
metadata:
  name: mconnect-nfproxy-ipv6
  labels:
    service.kubernetes.io/service-proxy-name: nfproxy
spec:
  ipFamily: IPv6
  selector:
    app: mconnect
  ports:
  - port: 5001
  type: LoadBalancer
  loadBalancerIP: "1000::1"
