#! /bin/sh
# NOTE: A common pattern is to specify "-" (stdout) as out-file,
#  so there must be NO log printouts to stdout!

dir=$(dirname $0); dir=$(readlink -f $dir)
tmp=/tmp/$USER/xcluster_$$
die() {
	echo "ERROR: $*" >&2
	rm -rf $tmp
	exit 1
}
log() {
	echo "INFO: $*" >&2
}

test -n "$1" || die "No out-file"

mkdir -p $tmp/sbin
cp -R $dir/default/* $tmp
cp $GOPATH/src/github.com/Nordix/ctraffic/*.yaml $tmp/etc/kubernetes

for n in ctraffic assign-lb-ip; do
	f=$GOPATH/bin/$n
	test -x $f || die "Not executable [$f]"
	cp $f $tmp/sbin
done

cd $tmp
tar cf "$1" *
cd - > /dev/null
rm -rf $tmp
