apiVersion: apps/v1
kind: Deployment
metadata:
  name: multus-server
spec:
  selector:
    matchLabels:
      app: multus-server
  replicas: 4
  template:
    metadata:
      labels:
        app: multus-server
      annotations:
        k8s.v1.cni.cncf.io/networks: ipvlan
    spec:
      containers:
      - name: alpine
        image: docker.io/library/alpine:latest
        imagePullPolicy: IfNotPresent
        command: ["sh", "-c", "nc -lk -p 5001 -e hostname"]
        securityContext:
          privileged: true
        ports:
        - name: hostname
          containerPort: 5001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multus-client
spec:
  selector:
    matchLabels:
      app: multus-client
  replicas: 4
  template:
    metadata:
      labels:
        app: multus-client
      annotations:
        k8s.v1.cni.cncf.io/networks: ipvlan
    spec:
      containers:
      - name: alpine
        image: docker.io/library/alpine:latest
        imagePullPolicy: IfNotPresent
        command: ["/usr/bin/tail", "-f", "/dev/null"]
        securityContext:
          privileged: true

