#! /bin/sh
# NOTE: A common pattern is to specify "-" (stdout) as out-file,
#  so there must be NO log printouts to stdout!

dir=$(dirname $0); dir=$(readlink -f $dir)
tmp=/tmp/$USER/xcluster_$$
die() {
	echo "ERROR: $*" >&2
	rm -rf $tmp
	exit 1
}
log() {
	echo "INFO: $*" >&2
}

test -n "$1" || die "No out-file"

mkdir -p $tmp
cp -R $dir/default/* $tmp

test -n "$IPERF_WORKSPACE" || IPERF_WORKSPACE=/tmp/$USER/iperf
x=$IPERF_WORKSPACE/bin/iperf
if test -x $x; then
	cp $x $tmp/bin
else
	which iperf > /dev/null || die "Iperf not found"
	$XCLUSTER install_prog --dest=$tmp iperf
fi

if test "$CNIBIN" = "yes"; then
	mkdir -p $tmp/opt/cni/bin
	x=$($XCLUSTER ovld cni-plugins)/cni-plugins.sh
	$x install --dest=$tmp/opt/cni/bin || die
fi

cd $tmp
tar cf "$1" *
cd - > /dev/null
rm -rf $tmp
