#! /bin/sh
# NOTE: A common pattern is to specify "-" (stdout) as out-file,
#  so there must be NO log printouts to stdout!

dir=$(dirname $0); dir=$(readlink -f $dir)
tmp=/tmp/$USER/xcluster_$$
die() {
	echo "ERROR: $*" >&2
	rm -rf $tmp
	exit 1
}
log() {
	echo "INFO: $*" >&2
}

test -n "$1" || die "No out-file"

mkdir -p $tmp
cp -R $dir/default/* $tmp

test -n "$IPERF_WORKSPACE" || IPERF_WORKSPACE=/tmp/$USER/iperf
x=$IPERF_WORKSPACE/bin/iperf
test -x $x || die "Not executable [$x]"
cp $x $tmp/bin

if test "$CNIBIN" = "yes"; then
	ar=$ARCHIVE/cni-plugins-linux-amd64-v1.0.1.tgz
	test -r $ar || ar=$HOME/Downloads/cni-plugins-linux-amd64-v1.0.1.tgz
	test -r $ar || die "Not readable [$ar]"
	log "Including cni-plugins-linux-amd64-v1.0.1 ..."
	mkdir -p $tmp//opt/cni/bin
	tar -C $tmp//opt/cni/bin -xf $ar
fi

cd $tmp
tar cf "$1" *
cd - > /dev/null
rm -rf $tmp
