#! /bin/sh

if test -z "$XCLUSTER_WORKSPACE"; then
	export XCLUSTER_WORKSPACE="$(readlink -f .)/workspace"
	if ! test -d "$XCLUSTER_WORKSPACE"; then
		mkdir -p "$XCLUSTER_WORKSPACE"
		cat <<EOF

The \$XCLUSTER_WORKSPACE is set to;

  XCLUSTER_WORKSPACE=$XCLUSTER_WORKSPACE

EOF
	fi
fi

test -n "$ARCHIVE" || export ARCHIVE=$HOME/Downloads
mkdir -p $ARCHIVE

vm() {
	local bg='#040'
	test "$1" -gt 200 && bg='#400'
	test "$1" -gt 220 && bg='#004'
	XXTERM=XCLUSTER exec xterm -T "vm-$1" -fg wheat -bg "$bg" \
		-e "telnet 192.168.0.$1" &
}
cdo() {
	cd $($XCLUSTER ovld $1)
}
_cdo_completion() {
	local XCLUSTER_OVLPATH d o
	eval $($XCLUSTER env | grep XCLUSTER_OVLPATH=)
	for d in $(echo $XCLUSTER_OVLPATH | tr : ' '); do
		test -d $d || continue
		o+=$(find $d -mindepth 1 -maxdepth 1 -type d -name "$2*" -printf "%f ")
	done
	COMPREPLY=($o)
}
complete -F _cdo_completion cdo

export XCLUSTER="$(readlink -f .)/xcluster.sh"
alias xc=$XCLUSTER

eval $($XCLUSTER env | grep -i DISKIM)
export DISKIM
alias diskim=$DISKIM

which mke2fs > /dev/null || export PATH=$PATH:/sbin:/usr/sbin

if ip netns id | grep -q -E "^${USER}_xcluster[0-9]+\$"; then
	# We are in a netns. Reset the $__net_setup is it is set for main
	# netns.
	echo $__net_setup | grep -q '/config/net-setup-userspace.sh' && \
		unset __net_setup
	return
fi

# We are not in a xcluster netns. Use user-space networking.

vm() {
	local bg='#040'
	test "$1" -gt 200 && bg='#400'
	test "$1" -gt 220 && bg='#004'
	local nodeid=$1
	local p=$((12000+nodeid))
	test -n "$XCLUSTER_TELNET_BASE" && p=$((XCLUSTER_TELNET_BASE+nodeid))
	XXTERM=XCLUSTER exec xterm -T "vm-$1" -fg wheat -bg "$bg" \
		-e "telnet 127.0.0.1 $p" &
}
export __net_setup="$(readlink -f .)/config/net-setup-userspace.sh"
