#! /bin/sh
# NOTE: A common pattern is to specify "-" (stdout) as out-file,
#  so there must be NO log printouts to stdout!

dir=$(dirname $0); dir=$(readlink -f $dir)
tmp=/tmp/$USER/xcluster_$$
die() {
	echo "ERROR: $*" >&2
	rm -rf $tmp
	exit 1
}
log() {
	echo "INFO: $*" >&2
}

test -n "$1" || die "No out-file"

mkdir -p $tmp
cp -R $dir/default/* $tmp
gcc -Wall -o $tmp/bin/tap-scrambler $dir/src/* || die Compile
$XCLUSTER install_prog --dest=$tmp ping

cd $tmp
tar cf "$1" *
cd - > /dev/null
rm -rf $tmp
