#! /bin/sh
# NOTE: A common pattern is to specify "-" (stdout) as out-file,
#  so there must be NO log printouts to stdout!

dir=$(dirname $0); dir=$(readlink -f $dir)
tmp=/tmp/$USER/xcluster_$$
die() {
	echo "ERROR: $*" >&2
	rm -rf $tmp
	exit 1
}
log() {
	echo "INFO: $*" >&2
}

test -n "$1" || die "No out-file"

eval $($XCLUSTER env)

mkdir -p $tmp
cp -R $dir/default/* $tmp
$XCLUSTER cploader --dest=$tmp

v=$(date +%y.%j)
sed -i -e "s,1.0,$v," $tmp/etc/os-release

f=$XCLUSTER_WORKSPACE/$__bbver/busybox
test -x $f || die "Not executable [$f]"

ip=$XCLUSTER_WORKSPACE/iproute2-$__ipver/ip/ip
test -x $ip || die "Not executable [$ip]"

# This will install all libs. Note that we don't want to exclude the base-libs!
__base_libs=/dev/null $XCLUSTER install_prog --dest=$tmp $f $ip strace tcpdump jq

# libnss_files.so is needed for /etc/services parsing
mkdir -p $tmp/lib/x86_64-linux-gnu
for n in libnss_files.so.2 libnss_dns.so.2 libresolv.so.2 libpthread.so.0; do
    f=/lib/x86_64-linux-gnu/$n
    test -r $f || die "Not readable [$f]"
    cp -L $f $tmp/lib/x86_64-linux-gnu
done

iptoolsd=$($XCLUSTER ovld iptools)
$iptoolsd/tar - | tar -C $tmp -x

ln -s busybox $tmp/bin/sh

cd $tmp
tar cf "$1" *
cd - > /dev/null
rm -rf $tmp
