#! /bin/sh
# NOTE: A common pattern is to specify "-" (stdout) as out-file,
#  so there must be NO log printouts to stdout!

dir=$(dirname $0); dir=$(readlink -f $dir)
tmp=/tmp/$USER/xcluster_$$
die() {
	echo "ERROR: $*" >&2
	rm -rf $tmp
	exit 1
}
log() {
	echo "INFO: $*" >&2
}

test -n "$1" || die "No out-file"

mkdir -p $tmp
for s in $(echo "$SETUP" | tr ',' ' '); do
	test -d $dir/$s || continue
	cp -R $dir/$s/* $tmp
	setup_copied=yes
done
test "$setup_copied" != "yes" && test -d $dir/default && cp -R $dir/default/* $tmp

$XCLUSTER install_prog --dest=$tmp wget

f=$GOPATH/src/github.com/Nordix/ipam-node-local/node-local
test -x $f || die "Not executable [$f]"
mkdir -p $tmp/opt/cni/bin
cp $f $tmp/opt/cni/bin

f=$GOPATH/bin/assign-lb-ip
test -x $f && cp $f $tmp/bin

cd $tmp
tar cf "$1" *
cd - > /dev/null
rm -rf $tmp
