apiVersion: v1
kind: Service
metadata:
  name: mconnect-ipv4
spec:
  serviceIPFamily: IPv4Service
  selector:
    app: mconnect
  ports:
  - port: 5001
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: mconnect-ipv6
spec:
  serviceIPFamily: IPv6Service
  selector:
    app: mconnect
  ports:
  - port: 5001
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mconnect-deployment
spec:
  selector:
    matchLabels:
      app: mconnect
  replicas: 4
  template:
    metadata:
      labels:
        app: mconnect
    spec:
      containers:
      - name: mconnect
        image: nordixorg/mconnect:v1.2
        ports:
        - containerPort: 5001
