apiVersion: apps/v1
kind: Deployment
metadata:
  name: metallb-controller
spec:
  selector:
    matchLabels:
      app: metallb-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: metallb-controller
    spec:
      containers:
      - name: metallb
        image: library/metallb:0.8.1
        securityContext:
          privileged: true

