apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: config
data:
  config: |
    peers:
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 10.0.0.0/28
      - 1000::/124
