apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: metallb-speaker
spec:
  selector:
    matchLabels:
      app: metallb-speaker
  template:
    metadata:
      labels:
        app: metallb-speaker
    spec:
      hostNetwork: true
      containers:
      - name: metallb
        image: library/metallb:latest
        command:
          - /bin/speaker
        securityContext:
          privileged: true
        env:
          - name: METALLB_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
