apiVersion: v1
kind: ConfigMap
metadata:
  name: sriovdp-config
  namespace: kube-system
data:
  config.json: |
    {
        "resourceList": [{
                "resourceName": "igb_82576",
                "selectors": {
                    "vendors": ["8086"],
                    "devices": ["10ca"],
                    "drivers": ["igbvf"]
                }
            }
        ]
    }
