#! /bin/sh
# NOTE: A common pattern is to specify "-" (stdout) as out-file,
#  so there must be NO log printouts to stdout!

dir=$(dirname $0); dir=$(readlink -f $dir)
tmp=/tmp/$USER/xcluster_$$
die() {
	echo "ERROR: $*" >&2
	rm -rf $tmp
	exit 1
}
log() {
	echo "INFO: $*" >&2
}

test -n "$1" || die "No out-file"

mkdir -p $tmp
cp -R $dir/default/* $tmp

mkdir -p $tmp/bin
f=$GOPATH/src/github.com/Nordix/mconnect/image/mconnect
test -x $f || f=$GOPATH/bin/mconnect
test -x $f || f=$XCLUSTER_WORKSPACE/bin/mconnect
if ! test -x $f; then
	# Check if mconnect.xz is downloaded
	ar=$ARCHIVE/mconnect.xz
	test -r $ar || ar=$HOME/Downloads/mconnect.xz
	test -r $ar || die "Could not find mconnect"
	xz -cd $ar > $tmp/bin/mconnect || die "xz -cd $ar"
	chmod a+x $tmp/bin/mconnect
else
	strip $f
	cp $f $tmp/bin
fi

cd $tmp
tar cf "$1" *
cd - > /dev/null
rm -rf $tmp
