#! /bin/sh
# NOTE: A common pattern is to specify "-" (stdout) as out-file,
#  so there must be NO log printouts to stdout!

dir=$(dirname $0); dir=$(readlink -f $dir)
tmp=/tmp/$USER/xcluster_$$
die() {
	echo "ERROR: $*" >&2
	rm -rf $tmp
	exit 1
}
log() {
	echo "INFO: $*" >&2
}

test -n "$1" || die "No out-file"

mkdir -p $tmp
cp -R $dir/default/* $tmp
test "$TEST" = "yes" && cp -R $dir/test/* $tmp

test -n "$TOPOLOGY" || TOPOLOGY=xnet
test -d $dir/$TOPOLOGY && cp -R $dir/$TOPOLOGY/* $tmp
rm -f $tmp/Envsettings $tmp/*.svg

n=$GOPATH/bin/coredns
test -x $n || n=$XCLUSTER_WORKSPACE/bin/coredns
test -x $n || die "Not executable [$n]"
mkdir -p $tmp/bin
cp $n $tmp/bin

cd $tmp
tar cf "$1" *
cd - > /dev/null
rm -rf $tmp
