#! /bin/sh
# NOTE: A common pattern is to specify "-" (stdout) as out-file,
#  so there must be NO log printouts to stdout!

dir=$(dirname $0); dir=$(readlink -f $dir)
tmp=/tmp/$USER/xcluster_$$
die() {
	echo "ERROR: $*" >&2
	rm -rf $tmp
	exit 1
}
log() {
	echo "INFO: $*" >&2
}

test -n "$1" || die "No out-file"

mkdir -p $tmp
cp -R $dir/default/* $tmp
for s in $(echo "$SETUP" | tr ',' ' '); do
	test -d $dir/$s || continue
	cp -R $dir/$s/* $tmp
done

$XCLUSTER install_prog --dest=$tmp ping
for x in mconnect ctraffic; do
	f=$GOPATH/src/github.com/Nordix/$x/image/$x
	if test -x $f; then
		log "Using local [$x]"
		cp $f $tmp/bin
	else
		ar=$ARCHIVE/$x.xz
		if test -r $ar; then
			unpack=xz
		else
			ar=$ARCHIVE/$x.gz						
			test -r $ar || die "Not found [$x]"
			unpack=gzip
		fi
		$unpack -dc $ar > $tmp/bin/$x
		chmod a+x $tmp/bin/$x
	fi
done

f=$XCLUSTER_WORKSPACE/libnetfilter_queue-1.0.3/examples/.libs/nf-queue
test -x $f && $XCLUSTER install_prog --dest=$tmp $f

if echo $SETUP | grep -q nfqueue; then
	ar=$(find $HOME/Downloads -name 'nfqlb-*.tar.xz' | sort -rV | head -1)
	test -n "$ar" || die 'Could not find: ~/Downloads/nfqlb-*.tar.xz'
	log "Using $(echo $ar | grep -Eo 'nfqlb-[0-9\.]+')"
	tar -xO --wildcards -f $ar '*/bin/nfqlb' > $tmp/bin/nfqlb
	chmod a+x $tmp/bin/nfqlb
fi

if echo $SETUP | grep -q dpdk; then
	test -n "$__dpdk_src" || die 'Not set [$__dpdk_src]'
	make -f $dir/src/dpdk/Makefile DIR=$dir/src/dpdk DST=$tmp/bin \
		2>&1 > /dev/null || die "make l2lb"
	mkdir -p $tmp/usr/local/lib
    cp -R $__dpdk_src/build/sys/usr/local/lib/x86_64-linux-gnu $tmp/usr/local/lib
	for n in libbsd.so.0 libfdt.so.1 libisal.so.2; do
		cp -L /usr/lib/x86_64-linux-gnu/$n $tmp/usr/local/lib/x86_64-linux-gnu
	done
fi

if echo $SETUP | grep -q xdp; then
	eval $($XCLUSTER env | grep __kobj)
	export __kobj
	mkdir -p $tmp/bin
	make -C $dir/src/xdp O=$tmp/bin > /dev/null 2>&1 || die "Make XDP"
	ksrc=$(readlink -f $__kobj/source)
	f=$ksrc/tools/bpf/bpftool/bpftool
	test -x $f || die "Not executable [$f]"
	cp $f $tmp/bin
fi

$XCLUSTER install_prog --dest=$tmp jq

cd $tmp
tar cf "$1" *
cd - > /dev/null
rm -rf $tmp
