#! /bin/sh
# NOTE: A common pattern is to specify "-" (stdout) as out-file,
#  so there must be NO log printouts to stdout!

dir=$(dirname $0); dir=$(readlink -f $dir)
tmp=/tmp/$USER/xcluster_$$
die() {
	echo "ERROR: $*" >&2
	rm -rf $tmp
	exit 1
}
log() {
	echo "INFO: $*" >&2
}

test -n "$1" || die "No out-file"

mkdir -p $tmp
cp -R $dir/default/* $tmp
for s in $(echo "$SETUP" | tr ',' ' '); do
	test -d $dir/$s || continue
	cp -R $dir/$s/* $tmp
done

f=$GOPATH/src/github.com/Nordix/mconnect/image/mconnect
test -x $f || die "Not executable [$f]"
cp $f $tmp/bin

f=$GOPATH/src/github.com/Nordix/ctraffic/image/ctraffic
test -x $f || die "Not executable [$f]"
cp $f $tmp/bin

f=$XCLUSTER_WORKSPACE/libnetfilter_queue-1.0.3/examples/.libs/nf-queue
test -x $f && $XCLUSTER install_prog --dest=$tmp $f

echo $SETUP | grep -q nfqueue && \
	gcc -o $tmp/bin/lb $dir/src/lb.c $dir/src/maglev.c -lmnl -lnetfilter_queue -lrt

$XCLUSTER install_prog --dest=$tmp jq

cd $tmp
tar cf "$1" *
cd - > /dev/null
rm -rf $tmp
