#! /bin/sh
# NOTE: A common pattern is to specify "-" (stdout) as out-file,
#  so there must be NO log printouts to stdout!

dir=$(dirname $0); dir=$(readlink -f $dir)
tmp=/tmp/$USER/xcluster_$$
die() {
	echo "ERROR: $*" >&2
	rm -rf $tmp
	exit 1
}
log() {
	echo "INFO: $*" >&2
}

test -n "$1" || die "No out-file"

mkdir -p $tmp
cp -R $dir/default/* $tmp
for s in $(echo "$SETUP" | tr ',' ' '); do
	test -d $dir/$s || continue
	cp -R $dir/$s/* $tmp
done

$XCLUSTER install_prog --dest=$tmp ping

f=$GOPATH/src/github.com/Nordix/mconnect/image/mconnect
test -x $f || die "Not executable [$f]"
cp $f $tmp/bin

f=$GOPATH/src/github.com/Nordix/ctraffic/image/ctraffic
test -x $f || die "Not executable [$f]"
cp $f $tmp/bin

cd $dir/src/udp-test
go build -ldflags "-extldflags '-static' -X main.version=$(date +%F:%T)" \
	-o $tmp/bin/udp-test main.go || die udp-test
cd $dir

f=$XCLUSTER_WORKSPACE/libnetfilter_queue-1.0.3/examples/.libs/nf-queue
test -x $f && $XCLUSTER install_prog --dest=$tmp $f

if echo $SETUP | grep -q nfqueue; then
	d=$GOPATH/src/github.com/Nordix/nfqueue-loadbalancer/src
	make -C $d X=$tmp/bin/nfqlb > /dev/null || die "Make nfqlb"
fi

if echo $SETUP | grep -q dpdk; then
	test -n "$__dpdk_src" || die 'Not set [$__dpdk_src]'
	make -f $dir/src/dpdk/Makefile DIR=$dir/src/dpdk DST=$tmp/bin \
		2>&1 > /dev/null || die "make l2lb"
	mkdir -p $tmp/usr/local/lib
    cp -R $__dpdk_src/build/sys/usr/local/lib/x86_64-linux-gnu $tmp/usr/local/lib
fi

if echo $SETUP | grep -q xdp; then
	eval $($XCLUSTER env | grep __kobj)
	export __kobj
	mkdir -p $tmp/bin
	make -C $dir/src/xdp O=$tmp/bin > /dev/null 2>&1 || die "Make XDP"
	ksrc=$(readlink -f $__kobj/source)
	f=$ksrc/tools/bpf/bpftool/bpftool
	test -x $f || die "Not executable [$f]"
	cp $f $tmp/bin
fi

$XCLUSTER install_prog --dest=$tmp jq

cd $tmp
tar cf "$1" *
cd - > /dev/null
rm -rf $tmp
