apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    peers:
    - peer-address: 192.168.1.201
      peer-asn: 65002
      my-asn: 65001
    - peer-address: 192.168.1.202
      peer-asn: 65002
      my-asn: 65001
    address-pools:
    - name: default
      protocol: bgp
      addresses:
      - 10.0.0.0/28
