#! /bin/sh

prg=$(basename $0)
dir=$(dirname $0); dir=$(readlink -f $dir)
tmp=/tmp/${prg}_$$
die() {
    echo "ERROR: $*" >&2
    rm -rf $tmp
    exit 1
}
log() {
    echo "iptools: $*" >&2
}
test -n "$1" || die "No out-file"

sysd=$XCLUSTER_WORKSPACE/sys
if ! test -x $sysd/usr/sbin/xtables-legacy-multi; then
	cat >&2 <<EOF

Iptools are not built. Please do;

  $dir/iptools.sh download
  $dir/iptools.sh build

EOF
	die "Iptools not built"
fi


eval $($dir/iptools.sh versions)

mkdir -p $tmp
cp -r $dir/default/* $tmp

mkdir -p $tmp/usr/sbin $tmp/usr/lib
cp -R $sysd/usr/sbin $tmp/usr
cp -R $sysd/usr/lib $tmp/usr
$XCLUSTER cplib --dest=$tmp $tmp/usr/sbin/ipvsadm

$XCLUSTER install_prog --dest=$tmp socat curl ethtool nstat

# Lib-to-lib dependecies enforces this;
LD_LIBRARY_PATH=$XCLUSTER_WORKSPACE/sys/usr/lib \
	$XCLUSTER cplib --dest=$tmp $tmp/usr/sbin/nft

# Install libraries
#$XCLUSTER cplib --dest=$tmp $tmp/usr/sbin/*

mkdir -p $tmp/usr/lib/x86_64-linux-gnu/
ln -s ../xtables $tmp/usr/lib/x86_64-linux-gnu/xtables

# Enforce "nf_tables" mode;
#cp $tmp/usr/sbin/xtables-nft-multi $tmp/usr/sbin/xtables-legacy-multi

# Clean-up work-around
rm -rf $tmp/$sysd $tmp/home $tmp/usr/lib/pkgconfig

if which nmap > /dev/null; then
	$XCLUSTER install_prog --dest=$tmp nmap ncat nping
fi

d=$XCLUSTER_WORKSPACE/iproute2-$iproute2/sys
if test -d $d; then
	log "Including iproute2-$iproute2..."
	cp -R $d/sbin $tmp
	$XCLUSTER cplib --dest=$tmp $d/sbin/ip
fi

f=$HOME/Downloads/iperf
if test -x $f; then
	cp $f $tmp/bin
elif which iperf > /dev/null; then
	$XCLUSTER install_prog --dest=$tmp iperf
fi

f=$XCLUSTER_WORKSPACE/ipset-$ipset7/src/ipset
if test -x $f; then
	cp $f $tmp/usr/sbin/ipset7
	log "ipset7 as ipset ver $ipset7"
fi

cd $tmp
tar cf "$1" *
cd - > /dev/null
rm -rf $tmp
