#! /bin/sh
# NOTE: A common pattern is to specify "-" (stdout) as out-file,
#  so there must be NO log printouts to stdout!

dir=$(dirname $0); dir=$(readlink -f $dir)
tmp=/tmp/$USER/xcluster_$$
die() {
	echo "ERROR: $*" >&2
	rm -rf $tmp
	exit 1
}
log() {
	echo "INFO: $*" >&2
}

test -n "$1" || die "No out-file"

mkdir -p $tmp
for s in $(echo "$SETUP" | tr ',' ' '); do
	test -d $dir/$s || continue
	cp -R $dir/$s/* $tmp
	setup_copied=yes
done
test "$setup_copied" != "yes" && test -d $dir/default && cp -R $dir/default/* $tmp

if test "$__auto_start" = "yes"; then
	destd=$tmp/etc/kubernetes/load
	srcd=$GOPATH/src/github.com/networkservicemesh/networkservicemesh/k8s/conf
	mkdir -p $tmp/etc/kubernetes/load
	export CA_BUNDLE='""'
	for f in namespace-nsm.yaml admission-webhook.yaml \
		admission-webhook-cfg.yaml cluster-role-admin.yaml \
		cluster-role-binding.yaml cluster-role-view.yaml \
		crd-networkserviceendpoints.yaml crd-networkservicemanagers.yaml \
		crd-networkservices.yaml nsmgr.yaml \
		; do

		test -r $srcd/$f || die "Not readable [$srcd/$f]"
		envsubst < $srcd/$f > $destd/$f
	done
fi

f=$GOPATH/bin/dpframework
test -x $f && cp $f $tmp/bin
f=$GOPATH/src/github.com/Nordix/dpframework/scripts/fakedev
test -x $f && cp $f $tmp/bin

d=$GOPATH/src/github.com/networkservicemesh/examples/examples/bridge-domain
test -d "$d/k8s" && cp -r "$d/k8s" $tmp/etc/kubernetes/bridge-domain

cd $tmp
tar cf "$1" *
cd - > /dev/null
rm -rf $tmp
