apiVersion: v1
kind: Service
metadata:
  name: busybox
spec:
  selector:
    app: busybox
  ports:
  - port: 1023
    targetPort: 23
    name: telnet
  - port: 1022
    targetPort: 22
    name: ssh
  - port: 1080
    targetPort: 80
    name: http
  externalIPs:
  - 1000::2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-deployment
spec:
  selector:
    matchLabels:
      app: busybox
  replicas: 4
  template:
    metadata:
      labels:
        app: busybox
    spec:
      dnsPolicy: Default
      containers:
      - name: busybox
        image: example.com/xcluster-busybox:0.1
        imagePullPolicy: Never
        ports:
        - containerPort: 23
          name: telnet
        - containerPort: 22
          name: ssh
        - containerPort: 80
          name: http
