#! /bin/sh

dir=$(dirname $0); dir=$(readlink -f $dir)
tmp=/tmp/xcluster_$$
die() {
    echo "ERROR: $*" >&2
    rm -rf $tmp
    exit 1
}
log() {
    echo "$*" >&2
}
test -n "$1" || die "No out-file"

rm -rf $tmp
mkdir -p $tmp/bin $tmp/sbin

for s in $(echo "$SETUP" | tr ',' ' '); do
        test -d $dir/$s || continue
        cp -R $dir/$s/* $tmp
        setup_copied=yes
done

if test "$setup_copied" = "yes"; then
	cd $tmp
	tar cf "$1" *
	cd - > /dev/null
	rm -rf $tmp
	exit 0
fi

cp -R $dir/default/* $tmp

# Some binaries can't be replaced by BusyBox applets
f=/bin/kmod
test -x $f || die "Not executable [$f]"
cp $f $tmp/sbin/modprobe
f=/usr/bin/find
test -x $f || die "Not executable [$f]"
cp $f $tmp/bin/find

test -n "$KUBERNETESD" || KUBERNETESD=$GOPATH/src/k8s.io/kubernetes/_output/bin
test -d "$KUBERNETESD" || die "Not a directory [$KUBERNETESD]"
f=$KUBERNETESD/hyperkube
if test -x $f; then
	cp $f $tmp/bin
else
	for n in kube-controller-manager kube-scheduler kube-apiserver \
		kube-proxy kubectl kubelet; do
		test -x $KUBERNETESD/$n || die "Not executable [$KUBERNETESD/$n]"
		cp $KUBERNETESD/$n $tmp/bin
	done
fi
mkdir -p $tmp/etc/kubernetes
$KUBERNETESD/kubectl version --client --short > $tmp/etc/kubernetes/version

# Install cri-o
f=$ARCHIVE/runc.amd64
test -x $f || die "Not executable [$f]"
mkdir -p $tmp/bin
cp $f $tmp/bin/runc
d=$GOPATH/src/github.com/cri-o/cri-o/bin
for f in crio crio-status; do
	test -x $d/$f || die "Not executable [$d/$f]"
	cp $d/$f $tmp/bin
done
f=$GOPATH/src/github.com/containers/conmon/bin/conmon
test -x $f || die "Not executable [$f]"
cp $f $tmp/bin
ver=v1.16.1
ar=$ARCHIVE/crictl-$ver-linux-amd64.tar.gz
test -r $ar || die "Not readable [$ar]"
tar -C $tmp/bin -xf $ar

# (until we have some hooks...)
mkdir -p $tmp/usr/share/containers/oci/hooks.d

# Certificates are required for image pull
mkdir -p $tmp/etc/ssl/certs
cp /etc/ssl/certs/ca-certificates.crt $tmp/etc/ssl/certs/

n=$GOPATH/bin/coredns
test -x $n || n=$(dirname $XCLUSTER)/bin/coredns
test -x $n && cp $n $tmp/bin

jq=$(which jq)
test -n "$jq" && cp $jq $tmp/bin
f=$GOPATH/bin/assign-lb-ip
test -x $f && cp $f $tmp/bin

# CNI-plugin loopback (required by K8s (kubelet))
ver=v0.8.2
ar=$HOME/Downloads/cni-plugins-linux-amd64-$ver.tgz
test -r "$ar" || die "Not readable [$ar]"
mkdir -p $tmp/opt/cni/bin
tar -C $tmp/opt/cni/bin -xf $ar ./loopback

# Install libraries
$XCLUSTER cplib --dest=$tmp $tmp/bin/*

cd $tmp
tar cf "$1" *
cd - > /dev/null
rm -rf $tmp
