#! /bin/sh
xcluster_prep() {
	case $1 in
		ipv4)
			SETUP="ipv4,$XSETUP"
			BASEOVLS=k8s-xcluster
			;;
		ipv6)
			SETUP="ipv6,$XSETUP"
			BASEOVLS=k8s-xcluster
			;;
		dual-stack)
			SETUP=$XSETUP
			;;
		*) ;;
	esac
}
