#! /bin/sh
# NOTE: A common pattern is to specify "-" (stdout) as out-file,
#  so there must be NO log printouts to stdout!

dir=$(dirname $0); dir=$(readlink -f $dir)
tmp=/tmp/$USER/xcluster_$$
die() {
	echo "ERROR: $*" >&2
	rm -rf $tmp
	exit 1
}
log() {
	echo "INFO: $*" >&2
}

test -n "$1" || die "No out-file"

skopeo=$ARCHIVE/skopeo
test -x $skopeo || skopeo=$GOPATH/bin/skopeo
test -x $skopeo || skopeo=$GOPATH/src/github.com/containers/skopeo/bin/skopeo
if ! test -x $skopeo; then
	which skopeo > /dev/null || die "Skopeo not found"
	skopeo=$(which skopeo)
fi
$skopeo -v >&2 || die "Skopeo not executable"
mkdir -p $tmp/bin
$XCLUSTER install_prog --dest=$tmp $skopeo



cd $tmp
tar cf "$1" *
cd - > /dev/null
rm -rf $tmp
