apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ipvlan
spec:
  config: '{
    "cniVersion": "0.4.0",
    "type": "ipvlan",
	"master": "eth2",
	"ipam": {
      "type": "whereabouts",
      "range": "4000::16.0.0.0/120",
      "gateway": "4000::16.0.0.0"
    }
  }'
