apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: multus-alpine
spec:
  selector:
    matchLabels:
      app: multus-alpine
  template:
    metadata:
      labels:
        app: multus-alpine
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
            { "name": "ipvlan" },
            { "name": "macvlan" },
            { "name": "host-device" }
        ]'
    spec:
      containers:
      - name: multus-alpine
        image: library/alpine:latest
        imagePullPolicy: IfNotPresent
        command:
          - /bin/sh
          - "-c"
          - "sleep 60m"
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
