#! /bin/sh
# NOTE: A common pattern is to specify "-" (stdout) as out-file,
#  so there must be NO log printouts to stdout!

dir=$(dirname $0); dir=$(readlink -f $dir)
tmp=/tmp/$USER/xcluster_$$
die() {
	echo "ERROR: $*" >&2
	rm -rf $tmp
	exit 1
}
log() {
	echo "INFO: $*" >&2
}

test -n "$1" || die "No out-file"

mkdir -p $tmp
cp -R $dir/default/* $tmp

f=$ARCHIVE/cni-plugins-linux-amd64-v1.0.1.tgz
test -r $f || die "Not readable [$f]"
mkdir -p $tmp/opt/cni/bin
tar -C $tmp/opt/cni/bin -xf $f ./host-local ./bridge ./loopback


cd $tmp
tar cf "$1" *
cd - > /dev/null
rm -rf $tmp
