#! /bin/sh
# NOTE: A common pattern is to specify "-" (stdout) as out-file,
#  so there must be NO log printouts to stdout!

dir=$(dirname $0); dir=$(readlink -f $dir)
tmp=/tmp/$USER/xcluster_$$

die() {
	echo "ERROR: $*" >&2
	rm -rf $tmp
	exit 1
}
log() {
	echo "INFO: $*" >&2
}

test -n "$1" || die "No out-file"

msh=$dir/../multus.sh
csh=$($XCLUSTER ovld cni-plugins)/cni-plugins.sh
test -x $csh || die "Not executable"

mkdir -p $tmp/root
cp -R $dir/default/* $tmp
$msh cparchives $tmp/root || die "cp archives"

f=$tmp/root/multus-installer.sh
v=$($msh version)
sed -i -e "s,__multus_ver=unknown,__multus_ver=$v," $f
v=$($csh version)
sed -i -e "s,__cnibin_ver=unknown,__cnibin_ver=$v," $f

f=$(which kubectl)
mkdir -p $tmp/bin
cp -L $f $tmp/bin

test -n "$WHEREABOUTS_DIR" || WHEREABOUTS_DIR=$GOPATH/src/github.com/k8snetworkplumbingwg/whereabouts
f=$WHEREABOUTS_DIR/bin/whereabouts
test -x $f && cp $f $tmp/root

test -n "$NODEANNOTATION_DIR" || NODEANNOTATION_DIR=$GOPATH/src/github.com/Nordix/ipam-node-annotation
f=$NODEANNOTATION_DIR/node-annotation
test -x $f && cp $f $tmp/root


cd $tmp
tar cf "$1" *
cd - > /dev/null
rm -rf $tmp
