#! /bin/sh
# NOTE: A common pattern is to specify "-" (stdout) as out-file,
#  so there must be NO log printouts to stdout!

dir=$(dirname $0); dir=$(readlink -f $dir)
tmp=/tmp/$USER/xcluster_$$

die() {
	echo "ERROR: $*" >&2
	rm -rf $tmp
	exit 1
}
log() {
	echo "INFO: $*" >&2
}
findf() {
	f=$ARCHIVE/$1
	test -r $f && return 0
	f=$HOME/Downloads/$1
	test -r $f
}

test -n "$1" || die "No out-file"

msh=$dir/../multus.sh
eval $($msh env)
csh=$($XCLUSTER ovld cni-plugins)/cni-plugins.sh
test -x $csh || die "Not executable"

mkdir -p $tmp/root
cp -R $dir/default/* $tmp
$msh cparchives $tmp/root || die "cp archives"
uuid > $tmp/root/sentinel

f=$tmp/root/multus-installer.sh
sed -i -e "s,__multus_ver=unknown,__multus_ver=$__multus_ver," $f
echo "multus_ver=$__multus_ver" >> $tmp/root/sentinel
v=$($csh version)
sed -i -e "s,__cnibin_ver=unknown,__cnibin_ver=$v," $f
echo "cnibin_ver=$v" >> $tmp/root/sentinel

which kubectl > /dev/null || die "No kubectl"
f=$(which kubectl)
mkdir -p $tmp/bin
cp -L $f $tmp/bin

if findf whereabouts-amd64; then
	chmod a+x $f
	v=$($f --version 2>&1 | grep whereabouts)
	log "Including $v"
	cp $f $tmp/root/whereabouts
	strip $tmp/root/whereabouts
fi

test -n "$NODEANNOTATION_DIR" || NODEANNOTATION_DIR=$GOPATH/src/github.com/Nordix/ipam-node-annotation
f=$NODEANNOTATION_DIR/_output/kube-node
if test -x $f; then
	log "Including kube-node ipam"
	cp $f $tmp/root
fi

test -n "$SRIOV_DIR" || SRIOV_DIR=$GOPATH/src/github.com/k8snetworkplumbingwg/sriov-cni
f=$SRIOV_DIR/build/sriov
if test -x $f; then
	log "Including sriov cni-plugin"
	cp $f $tmp/root
fi


cd $tmp
tar cf "$1" *
cd - > /dev/null
rm -rf $tmp
