#! /bin/sh
# NOTE: A common pattern is to specify "-" (stdout) as out-file,
#  so there must be NO log printouts to stdout!

dir=$(dirname $0); dir=$(readlink -f $dir)
tmp=/tmp/$USER/xcluster_$$
die() {
	echo "ERROR: $*" >&2
	rm -rf $tmp
	exit 1
}
log() {
	echo "INFO: $*" >&2
}

mkdir -p $tmp
test -n "$1" || die "No out-file"
cp -R $dir/default/* $tmp
NFQLB_DIR=$HOME/tmp/nfqlb
nfqlb=$NFQLB_DIR/bin/nfqlb
if test -x $nfqlb; then
	log "Including nfqlb"
	cp $nfqlb $tmp/bin
else
	log "Nfqlb not included"
fi

d=$GOPATH/src/github.com/sctplab/usrsctp
x=$d/programs/echo_server
if test -x $x; then
	log "Including; echo_server"
	cp $x $tmp/bin
fi

make -s -C $dir/src clean > /dev/null 2>&1
make -s -C $dir/src -j$(nproc) X=$tmp/bin/sctpt static > /dev/null 2>&1 || die make

cd $tmp
tar cf "$1" *
cd - > /dev/null
rm -rf $tmp
