apiVersion: apps/v1
kind: Deployment
metadata:
  name: multus-alpine-bridge
spec:
  replicas: 10
  selector:
    matchLabels:
      app: multus-alpine-bridge
  template:
    metadata:
      labels:
        app: multus-alpine-bridge
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
            { "name": "bridge2" }
        ]'
    spec:
      containers:
      - name: multus-alpine-bridge
        image: docker.io/library/alpine:latest
        imagePullPolicy: IfNotPresent
        command: ["tail", "-f", "/dev/null"]
