apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bridge2
spec:
  config: '{
    "cniVersion": "0.4.0",
    "type": "bridge",
    "bridge": "mbr1",
    "isGateway": true,
	"ipam": {
      "type": "host-local",
      "ranges": [
        [{"subnet": "172.30.1.0/24"}],
        [{"subnet": "1000::1:172.30.1.0/120"}]
	  ]
    }
  }'
