apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bridge
spec:
  config: '{
     "cniVersion": "0.3.1",
     "type": "bridge",
     "bridge": "cbr0",
     "isGateway": true,
     "isDefaultGateway": true,
     "ipam": {
         "type": "node-local",
         "cfg": "default"
     }
}'
