#! /bin/sh
/bin/busybox echo "Xcluster starting..."
/bin/busybox mkdir -p /proc /sys /tmp /dev/pts /dev/shm /var/log \
	/sbin /usr/bin /usr/sbin /dev/mqueue
/bin/busybox rm -f /etc/mtab
/bin/busybox mount -t proc proc /proc
/bin/busybox --install -s
mount -t sysfs sysfs /sys
mdev -s

mkdir -p /run /var/log/dumps /var/tmp
ln -s /run /var/run

mount /tmp

echo /sbin/mdev > /proc/sys/kernel/hotplug

mount /dev/shm
mount /dev/pts
mount -o remount -w /
mdev -s
mount /dev/mqueue
mount -t cgroup2 cgroup2 /sys/fs/cgroup

# Get data from cdrom
mkdir -p /mnt
if mount -t iso9660 /dev/vdb /mnt > /dev/null 2>&1; then
	for n in $(find /mnt -name '*.tar' | sort); do
		EXTRACT_UNSAFE_SYMLINKS=1 tar -C / -o -xf $n
	done
	umount /mnt
fi

sysctl -p > /dev/null
test -d /lib/modules && depmod
ldconfig

test -r /etc/init.d/init.hook && . /etc/init.d/init.hook

exec /sbin/init
