apiVersion: apps/v1
kind: Deployment
metadata:
  name: metallb-controller
spec:
  selector:
    matchLabels:
      app: metallb-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: metallb-controller
    spec:
      hostNetwork: true
      containers:
      - name: metallb
        image: library/metallb:__controller_version
        securityContext:
          privileged: true
        livenessProbe:
          tcpSocket:
            port: 7472
          initialDelaySeconds: 3
          periodSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 7472
          initialDelaySeconds: 0
          periodSeconds: 5
