apiVersion: v1
kind: Service
metadata:
  name: alpine
spec:
  ipFamilyPolicy: RequireDualStack
  selector:
    app: alpine
  type: LoadBalancer
  allocateLoadBalancerNodePorts: false
  ports:
  - port: 6000
    name: nc
