#! /bin/sh
# NOTE: A common pattern is to specify "-" (stdout) as out-file,
#  so there must be NO log printouts to stdout!

dir=$(dirname $0); dir=$(readlink -f $dir)
tmp=/tmp/$USER/xcluster_$$
die() {
	echo "ERROR: $*" >&2
	rm -rf $tmp
	exit 1
}
log() {
	echo "INFO: $*" >&2
}

test -n "$1" || die "No out-file"

findar() {
	ar=$ARCHIVE/$1
	test -r $ar && return 0
	ar=$HOME/Downloads/$1
	test -r $ar
}

mkdir -p $tmp/bin
cp -R $dir/default/* $tmp

findar mconnect.xz || die "Can't find mconnect.xz"
xzcat $ar > $tmp/bin/mconnect
chmod a+x $tmp/bin/mconnect

findar ctraffic.gz || die "Can't find ctraffic.gz"
zcat $ar > $tmp/bin/ctraffic
chmod a+x $tmp/bin/ctraffic

if findar kahttp.xz; then
	xzcat $ar > $tmp/bin/kahttp
	chmod a+x $tmp/bin/kahttp
	if findar server.crt; then
		mkdir -p $tmp/root
		cp $ar $tmp/root
	else
		log "WARNING: kahttp server.crt not included"
	fi
else
	log "WARNING: kahttp not included"
fi

# Use locally built executables if they exist
for n in ctraffic mconnect kahttp; do
	f=$GOPATH/src/github.com/Nordix/$n/image/$n
	test -x $f || continue
	cp $f $tmp/bin
done

for n in ctraffic mconnect kahttp; do
	test -x $tmp/bin/$n || continue
	echo "$n:$($tmp/bin/$n -version)" >&2
done

sctpd=$($XCLUSTER ovld sctp)
make -s -C $sctpd/src clean > /dev/null 2>&1
make -s -C $sctpd/src -j$(nproc) X=$tmp/bin/sctpt static > /dev/null 2>&1 && \
	log "Including sctpt"


cd $tmp
tar cf "$1" *
cd - > /dev/null
rm -rf $tmp
