apiVersion: apps/v1
kind: Deployment
metadata:
  name: mserver
spec:
  replicas: 8
  selector:
    matchLabels:
      app: mserver
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: mserver
    spec:
      #terminationGracePeriodSeconds: 4
      containers:
      - name: mserver
        image: registry.nordix.org/cloud-native/mserver:latest
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command: ["sleep","2"]
        securityContext:
          privileged: true
        ports:
        - name: ctraffic
          containerPort: 5003
---
apiVersion: v1
kind: Service
metadata:
  name: mserver
spec:
  ipFamilyPolicy: RequireDualStack
  selector:
    app: mserver
  type: LoadBalancer
  allocateLoadBalancerNodePorts: false
  ports:
  - port: 5003
    name: ctraffic
