#! /bin/sh
##
## xctest --
##
##   Perform tests of the "xcluster" platform.
##
## Commands;
##

prg=$(basename $0)
dir=$(dirname $0); dir=$(readlink -f $dir)
tmp=/tmp/${prg}_$$

die() {
    echo "ERROR: $*" >&2
    rm -rf $tmp
    exit 1
}
help() {
    grep '^##' $0 | cut -c3-
    rm -rf $tmp
    exit 0
}
test -n "$1" || help
echo "$1" | grep -qi "^help\|-h" && help

log() {
	echo "$prg: $*" >&2
}
dbg() {
	test -n "$__verbose" && echo "$prg: $*" >&2
}

##  tcase_nodes
cmd_tcase_check_nodes() {
	test_nodes
}
cmd_tcase_check_namespaces() {
	test_namespaces
}
cmd_tcase_check_coredns() {
	test_coredns
}

cmd_tcase_start_local_controller() {
	tcase "Start local controller"
	$kubectl apply -f /etc/kubernetes/metallb.yaml || tdie
}
cmd_tcase_check_local_controller() {
	tcase "Check local controller"
	tex "npods metallb-controller- 1" || tdie
}
cmd_tcase_start_local_speaker() {
	tcase "Start local speaker"
	$kubectl apply -f /etc/kubernetes/metallb-speaker.yaml || tdie
}
cmd_tcase_check_local_speaker() {
	tcase "Check local speaker"
	tex "npods metallb-speaker- 4" || tdie
}

cmd_tcase_start_local_metallb() {
	cmd_tcase_start_local_controller
	cmd_tcase_start_local_speaker
	cmd_tcase_check_local_controller
	cmd_tcase_check_local_speaker
}

cmd_tcase_start_controller_version() {
	tcase "Starting metallb controller ver [$1]"
	test -n "$1" || tdie "No version"
	local f=/etc/metallb/metallb-controller-version.yaml
	sed -i -e "s,__controller_version,$1," $f || tdie
	$kubectl apply -f $f || tdie
	# Do not check here! We want to measure the readiness time.
}

pod_ready() {
	local pat=".status.conditions[]|select(.type == \"Ready\")|.status"
	local status=$(kubectl get pod -o json $1 | jq -r "$pat")
	echo "Ready = $status"
	test "$status" = "True"
}

cmd_tcase_controller_ready() {
	tcase "Check controller ready status"
	local begin=$(date +%s)
	local pod=$($kubectl -o json get pods -l 'app=metallb-controller' | jq -r .items[0].metadata.name)
	local timeout=10
	pushv $timeout $timeout 1
	tex "pod_ready $pod" || tdie
	popv
	local now=$(date +%s)
	tlog "Controller ready after $((now-begin)) seconds"
}

get_lbip() {
	$kubectl get svc $1 -o json | jq -r .status.loadBalancer.ingress[0].ip \
		| grep -v null
}

cmd_tcase_lbip_assigned() {
	tcase "Check svc $1 for assigned lbip $2"
	test -n "$1" || tdie "No svc"
	test -n "$2" || tdie "No lbip"
	tex "get_lbip $1" || tdie
	local lbip=$(get_lbip $1)
	test "$lbip" = "$2" || tdie "Lbip [$lbip], expected [$2]"
}

cmd_tcase_start_mconnect_dual_stack() {
	tcase "Start mconnect with dual-stack config"
	$kubectl apply -f /etc/kubernetes/mconnect-dual-stack.yaml || tdie
	tex "npods mconnect-deployment- 4" || tdie
}

cmd_tcase_check_svc_dual_stack() {
	tcase "Check dual-stack services"
	local pat='.status.loadBalancer.ingress[0].ip'
	local ip=$($kubectl get svc mconnect-ipv4 -o json | jq -r $pat)
	test "$ip" = "10.0.0.0" || tdie "Unexpected ipv4 [$ip]"
	ip=$($kubectl get svc mconnect-ipv6 -o json | jq -r $pat)
	test "$ip" = "1000::" || tdie "Unexpected ipv6 [$ip]"
}

external_traffic() {
	do_mconnect $1 && check_mconnect_result $tmp/out
}

cmd_tcase_external_traffic() {
	tcase "External to $1"
	test -n "$1" || tdie 'No address'
	pushv 60 20 3
	tex "external_traffic $1" || tdie
	popv
}

# Image-loading in user-space network will fail if we go via the routers.
cmd_tcase_set_default_route() {
	tcase "Default ipv4 route to 192.168.0.250"
	ip route replace default via 192.168.0.250 || tdie
}

##  tcase_config [config]
cmd_tcase_configure_metallb() {
	tcase "Configure metallb $1"
	test -n "$1" || tdie "No config"
	kubectl apply -f /etc/kubernetes/$1 || tdie
}

##  tcase_start_metallb
cmd_tcase_start_metallb() {
	local f=/etc/kubernetes/metallb-orig.yaml
	local v=$(grep 'image: metallb/controller:' $f | cut -d: -f3)
	tcase "Start metallb version $v"

	kubectl apply -f $f || tdie
	sleep 2
	kubectl='kubectl -n metallb-system'
	pushv 100 25 4
	local pod=controller-
	tex "npods $pod 1" || tdie
	pod=speaker-
	tex "npods $pod 4" || tdie
	popv
	return 0
}

cmd_tcase_start_mconnect() {
	start_mconnect /etc/kubernetes/mconnect.yaml || tdie
}

cmd_tcase_lbip() {
	tcase "LoadBalancerIP: $1 $2"
	tex "kubectl get svc $1 | ogrep $2"
}

check_peers() {
	mkdir -p $tmp
	local out=$tmp/out
	gobgp neighbor > $out
	cat $out
	local i
	for i in 1 2 3 4; do
		grep -E "$1$i .*Establ" $out || return 1
	done
	return 0
}
cmd_tcase_peers() {
	tcase "Check peers"
	tex "check_peers $1"
}

cmd_tcase_check_connectivity() {
	tcase "Check connectivity"
	tex "mconnect -address 10.0.0.0:5001 -nconn 4" || tdie
	tex "mconnect -address [1000::]:5001 -nconn 4" || tdie
}

cmd_tcase_mconnect() {
	tcase "Mconnect to [$1]"
	tex "do_mconnect $1"
}




cmd_tcase_lroute() {
	tcase "Local route to [$1] on $(hostname)"
	if echo $1 | grep -q : ; then
		ip -6 ro add $1 via 1000::1:192.168.1.201
	else
		ip ro add $1 via 192.168.1.201
	fi
}

cmd_tcase_multiaddr() {
	tcase "Add multi address [$1]"
	if echo $1 | grep -q : ; then
		ip -6 addr add $1 dev lo
		ip -6 ro add local $1 dev lo
	else
		ip addr add $1 dev lo
	fi
	sysctl -w net.ipv4.ip_nonlocal_bind=1
	sysctl -w net.ipv6.ip_nonlocal_bind=1
}

cmd_tcase_tplocal() {
	tcase "Traffic policy local"
	mkdir -p $tmp
	local out=$tmp/out
	wget -q -O - http://$1:8080/healthz > $out || tdie
	cat $out
	if echo "$1" | grep -q : ; then
		grep ',\[1000::1:c0a8:1c9\]' $out || tdie
	else
		grep ",192.168.1.201" $out || tdie
	fi
}

cmd_tcase_multi_mconnect() {
	tcase "Multi-address mconnect from [$2] to $1"
	mkdir -p $tmp
	local out=$tmp/out
	if ! mconnect -address $1:5001 -nconn 100 -output json -srccidr $2 -seed 8 > $out; then
		cat $out | jq .
		return 1
	fi
	check_mconnect_result $out
	
}

cmd_tcase_configure_routes() {
	tcase "Configure ipv6 routes"
	ip -6 route replace 1000::/124 \
		nexthop via 1000::1:192.168.1.1 \
		nexthop via 1000::1:192.168.1.2 \
		nexthop via 1000::1:192.168.1.3 \
		nexthop via 1000::1:192.168.1.4 || tdie
}

cmd_tcase_configure_l2_routing() {
	tcase "Configure L2 routing for ipv4 and ipv6"
	ip route add 10.0.0.0/28 dev eth1 || tdie
	ip -6 route add 1000::/124 dev eth1 || tdie
}

. /etc/profile
. /usr/lib/xctest

# Get the command
cmd=$1
shift
grep -q "^cmd_$cmd()" $0 $hook || die "Invalid command [$cmd]"

while echo "$1" | grep -q '^--'; do
    if echo $1 | grep -q =; then
	o=$(echo "$1" | cut -d= -f1 | sed -e 's,-,_,g')
	v=$(echo "$1" | cut -d= -f2-)
	eval "$o=\"$v\""
    else
	o=$(echo "$1" | sed -e 's,-,_,g')
	eval "$o=yes"
    fi
    shift
done
unset o v
long_opts=`set | grep '^__' | cut -d= -f1`

# Execute command
trap "die Interrupted" INT TERM
cmd_$cmd "$@"
status=$?
rm -rf $tmp
exit $status
