#! /bin/sh

dir=$(dirname $0); dir=$(readlink -f $dir)
tmp=/tmp/${prg}_$$
die() {
    echo "ERROR: $*" >&2
    rm -rf $tmp
    exit 1
}

test -n "$1" || die "No out-file"

rm -rf $tmp
mkdir -p $tmp/bin
if test "$TEST" = "yes"; then
	cp -R $dir/test/* $tmp
	if test "$__ipv6" = "yes"; then
		cp -R $dir/ipv6/* $tmp
	else
		cp -R $dir/default/* $tmp
	fi
else
	cp -R $dir/default/* $tmp
fi

$dir/etcd.sh download
$dir/etcd.sh etcd $tmp/bin

cd $tmp
tar cf "$1" *
cd - > /dev/null
rm -rf $tmp
