apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctraffic-deployment
spec:
  selector:
    matchLabels:
      app: ctraffic-deployment
  strategy:
    rollingUpdate:
      maxSurge: 0%
      maxUnavailable: 25%
    type: RollingUpdate
  replicas: 4
  template:
    metadata:
      labels:
        app: ctraffic-deployment
    spec:
      containers:
      - name: ctraffic
        image: registry.nordix.org/cloud-native/ctraffic:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5003
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ctraffic
spec:
  selector:
    matchLabels:
      app: ctraffic
  template:
    metadata:
      labels:
        app: ctraffic
    spec:
      containers:
      - name: ctraffic
        image: registry.nordix.org/cloud-native/ctraffic:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5003
---
apiVersion: v1
kind: Service
metadata:
  name: ctraffic
spec:
  selector:
    app: ctraffic
  ports:
  - port: 5003
---
apiVersion: v1
kind: Service
metadata:
  name: ctraffic-lb
spec:
  selector:
    app: ctraffic
  ports:
  - port: 5003
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: ctraffic-deployment
spec:
  selector:
    app: ctraffic-deployment
  ports:
  - port: 5003
---
apiVersion: v1
kind: Service
metadata:
  name: ctraffic-deployment-lb
spec:
  selector:
    app: ctraffic-deployment
  ports:
  - port: 5003
  type: LoadBalancer
