apiVersion: apps/v1
kind: Deployment
metadata:
  name: usrsctp-client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: usrsctp-client
  template:
    metadata:
      labels:
        app: usrsctp-client
    spec:
      serviceAccount: default
      nodeSelector:
        kubernetes.io/hostname: vm-002
      containers:
      - name: usrsctp-client
        imagePullPolicy: Always
        image: registry.nordix.org/cloud-native/usrsctp-test:latest
        env:
        - name: NO_SERVERS
          value: "yes"
        - name: LOCAL_IP_ADDR
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        securityContext:
          privileged: true
