apiVersion: apps/v1
kind: Deployment
metadata:
  name: metallb
spec:
  selector:
    matchLabels:
      app: metallb
  replicas: 1
  template:
    metadata:
      labels:
        app: metallb
    spec:
      hostNetwork: true
      containers:
      - name: metallb
        image: library/metallb:0.8.1
        securityContext:
          privileged: true

