apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: config
data:
  config: |
    peers:
    - peer-address: 1000::1:192.168.1.201
      peer-asn: 65002
      my-asn: 65001
    - peer-address: 1000::1:192.168.1.201
      peer-asn: 65002
      my-asn: 65001
    address-pools:
    - name: default
      protocol: bgp
      addresses:
      - 1000::/112
