#! /bin/sh

export __nrouters=6
export __nets201=0,1,3,4
export __nets202=0,2,7,8
export __nets203=0,3,5,9,11
export __nets204=0,4,6,9,12
export __nets205=0,5,7,10,12
export __nets206=0,6,8,10,11
test -n "$__mem201" || export __mem201=128
test -n "$__mem202" || export __mem202=128
test -n "$__mem203" || export __mem203=128
test -n "$__mem204" || export __mem204=128
test -n "$__mem205" || export __mem205=128
test -n "$__mem206" || export __mem206=128

test -z "$__ntesters" && export __ntesters=1
test $__ntesters -eq 0 && export __ntesters=1

if ip netns id | grep -q _xcluster; then
	# Ensure bridges for net 3-6
	for i in 3 4 5 6 7 8 9 10 11 12; do
		if ! ip link show xcbr$i > /dev/null 2>&1; then
			$XCLUSTER br_setup $i || echo "ERROR: could not create xcbr$i"
		fi
	done
fi
