---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nsc
  labels:
    app: nsc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nsc
  template:
    metadata:
      labels:
        app: nsc
    spec:
      terminationGracePeriodSeconds: 1
      containers:
        - image: registry.nordix.org/cloud-native/nsm/nsc:latest
#          imagePullPolicy: IfNotPresent
          name: nsc
          env:
            - name: NSM_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NSM_NETWORK_SERVICES
              value: kernel://icmp-responder/nsm-1
            - name: SPIFFE_ENDPOINT_SOCKET
              value: unix:///run/spire/sockets/agent.sock
            - name: NSC_OLD
              value: "no"
            - name: NSC_SERVICE
              value: "icmp-responder"
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
              readOnly: true
            - name: nsm-socket
              mountPath: /var/lib/networkservicemesh
              readOnly: true
      volumes:
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: Directory
        - name: nsm-socket
          hostPath:
            path: /var/lib/networkservicemesh
            type: DirectoryOrCreate
