---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nse
  labels:
    app: nse
spec:
  selector:
    matchLabels:
      app: nse
  template:
    metadata:
      labels:
        app: nse
    spec:
      nodeSelector:
        kubernetes.io/hostname: vm-003
      containers:
        - name: nse
          image: registry.nordix.org/cloud-native/nsm/cmd-nse-icmp-responder:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: SPIFFE_ENDPOINT_SOCKET
              value: unix:///run/spire/sockets/agent.sock
            - name: NSE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NSE_CONNECT_TO
              value: unix:///var/lib/networkservicemesh/nsm.io.sock
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
              readOnly: true
            - name: nsm-socket
              mountPath: /var/lib/networkservicemesh
              readOnly: false
      volumes:
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: Directory
        - name: nsm-socket
          hostPath:
            path: /var/lib/networkservicemesh
            type: DirectoryOrCreate
