#! /bin/sh
# NOTE: A common pattern is to specify "-" (stdout) as out-file,
#  so there must be NO log printouts to stdout!

dir=$(dirname $0); dir=$(readlink -f $dir)
tmp=/tmp/$USER/xcluster_$$
die() {
	echo "ERROR: $*" >&2
	rm -rf $tmp
	exit 1
}
log() {
	echo "INFO: $*" >&2
}

test -n "$1" || die "No out-file"

mkdir -p $tmp
cp -R $dir/default/* $tmp

cniver=v1.0.1
ar=$ARCHIVE/cni-plugins-linux-amd64-$cniver.tgz
test -r $ar || ar=$HOME/Downloads/cni-plugins-linux-amd64-$cniver.tgz
if test -r $ar; then
	mkdir -p $tmp/opt/cni/bin
	tar -C $tmp/opt/cni/bin -xf $ar
fi

ipu=$HOME/bin/ipu
test -x $ipu || ipu=$NFQLBDIR/bin/ipu
test -x $ipu && cp $ipu $tmp/bin

mkdir $tmp/etc
seq 1 254 | shuf > $tmp/etc/rnd-addresses

cd $tmp
tar cf "$1" *
cd - > /dev/null
rm -rf $tmp
