#! /bin/sh
# NOTE: A common pattern is to specify "-" (stdout) as out-file,
#  so there must be NO log printouts to stdout!

dir=$(dirname $0); dir=$(readlink -f $dir)
tmp=/tmp/$USER/xcluster_$$
die() {
	echo "ERROR: $*" >&2
	rm -rf $tmp
	exit 1
}
log() {
	echo "INFO: $*" >&2
}

test -n "$1" || die "No out-file"
mkdir -p $tmp
cp -R $dir/default/* $tmp

test -n "$coredns_ver" || coredns_ver=1.8.1
ar=$ARCHIVE/coredns_${coredns_ver}_linux_amd64.tgz
test -r $ar || die "Not readable [$ar]"
tar -C $tmp/bin -xf $ar


cd $tmp
tar cf "$1" *
cd - > /dev/null
rm -rf $tmp
