#! /bin/sh

dir=$(dirname $0); dir=$(readlink -f $dir)
tmp=/tmp/$USER/xcluster_$$
die() {
    echo "ERROR: $*" >&2
    rm -rf $tmp
    exit 1
}
log() {
    echo "INFO: $*" >&2
}

test -n "$1" || die "No out-file"

prg=$GOPATH/bin/coredns
test -x $prg || die "Not executable [$prg]"

mkdir -p $tmp/bin
cp $prg $tmp/bin

for s in $(echo "$SETUP" | tr ',' ' '); do
	test -d $dir/$s || continue
	cp -R $dir/$s/* $tmp
	setup_copied=yes
done
test "$setup_copied" != "yes" && cp -R $dir/default/* $tmp

which jq > /dev/null || die "Can't find [jq]"
cp $(which jq) $tmp/bin

$XCLUSTER cplib --dest=$tmp $tmp/bin/*
$XCLUSTER cploader --dest=$tmp $tmp

cd $tmp
tar cf "$1" *
cd - > /dev/null
rm -rf $tmp
