#! /bin/sh

dir=$(dirname $0); dir=$(readlink -f $dir)
tmp=/tmp/$USER/xcluster_$$
die() {
    echo "ERROR: $*" >&2
    rm -rf $tmp
    exit 1
}
log() {
    echo "INFO: $*" >&2
}

test -n "$1" || die "No out-file"

prg=$GOPATH/bin/coredns
test -x $prg || prg=$(dirname $XCLUSTER)/bin/coredns
test -x $prg || die "Not executable [$prg]"

mkdir -p $tmp/bin
cp $prg $tmp/bin

mkdir -p $tmp
base=$($XCLUSTER ovld k8s-base)
$base/image/tar - | tar -C $tmp -x

which jq > /dev/null || die "Can't find [jq]"
cp $(which jq) $tmp/bin

$XCLUSTER cplib --dest=$tmp $tmp/bin/*

cp -r $dir/default/* $tmp

cd $tmp
tar cf "$1" *
cd - > /dev/null
rm -rf $tmp
