apiVersion: v1
kind: Service
metadata:
  name: usrsctp
spec:
  externalTrafficPolicy: Local
  ipFamilyPolicy: PreferDualStack
  selector:
    app: usrsctp-server
  ports:
  - port: 7002
    name: usrsctpt-server
    protocol: SCTP
  type: LoadBalancer
