---
apiVersion: v1
kind: Service
metadata:
  name: usrsctp
  # labels:
  #   service.kubernetes.io/service-proxy-name: kpng-lb-proxier
spec:
  allocateLoadBalancerNodePorts: false
  ipFamilyPolicy: PreferDualStack
  selector:
    app: usrsctp-server
  ports:
  - port: 7002
    name: usrsctpt-server
    protocol: SCTP
  type: LoadBalancer
