---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: tg-conf
spec:
  config: '{
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": "vlan",
          "capabilities": { "ips": true },
          "master": "{{ .Values.tgMasterItf }}",
          "vlanId": {{ .Values.tgVlanId }},
          "ipam": {
            "type": "static",
            "routes": [
                        { "dst": "20.0.0.1/32", "gw": "{{ regexReplaceAllLiteral "/[0-9]+" .Values.gwtg1IPv4 "" }}" },
                        { "dst": "20.0.0.1/32", "gw": "{{ regexReplaceAllLiteral "/[0-9]+" .Values.gwtg2IPv4 "" }}" },
                        { "dst": "2000::1/128", "gw": "{{ regexReplaceAllLiteral "/[0-9]+" .Values.gwtg1IPv6 "" }}" },
                        { "dst": "2000::1/128", "gw": "{{ regexReplaceAllLiteral "/[0-9]+" .Values.gwtg2IPv6 "" }}" }
                    ]
          }
        }
      ]
    }'
---
apiVersion: v1
kind: Pod
metadata:
  name: tg
  labels:
    app: tg
  annotations:
      k8s.v1.cni.cncf.io/networks: '[
        { "name": "tg-conf",
          "ips": [ "{{ .Values.tg1IPv4 }}", "{{ .Values.tg1IPv6 }}" ],
          "interface": "tg"
        }]'
spec:
#  tolerations:
#  - key: "gw"
#    operator: "Exists"
#  nodeSelector:
#    gw: "true"
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - "gateway"
        topologyKey: kubernetes.io/hostname
  containers:
        - name: ctraffic
          image: {{ .Values.registry }}/{{ .Values.organization }}/ctraffic:latest
          imagePullPolicy: {{ .Values.pullPolicy }}
          securityContext:
            privileged: true
#        - name: bird
#          image: {{ .Values.registry }}/{{ .Values.organization }}/{{ .Values.gatewayImage }}:{{ .Values.gatewayImageVer }}
#          imagePullPolicy: IfNotPresent
#          securityContext:
#            privileged: true
#          command: [ "/bin/bash", "-c", "--" ]
#          args: [ "while true; do sleep 30; done;" ]

