#! /bin/sh
# NOTE: A common pattern is to specify "-" (stdout) as out-file,
#  so there must be NO log printouts to stdout!

dir=$(dirname $0); dir=$(readlink -f $dir)
tmp=/tmp/$USER/xcluster_$$
die() {
	echo "ERROR: $*" >&2
	rm -rf $tmp
	exit 1
}
log() {
	echo "INFO: $*" >&2
}

modmaster() {
	local f=$($XCLUSTER ovld k8s-xcluster)/$1/etc/init.d/31kube-master.rc
	test -r $f || die "Not readable [$f]"
	mkdir -p $tmp/etc/init.d
	dst=$tmp/etc/init.d/31kube-master.rc
	sed -e 's,--allocate-node-cidrs=true,,' < $f > $dst
	chmod a+x $dst
}

test -n "$1" || die "No out-file"

mkdir -p $tmp
for s in $(echo "$SETUP" | tr ',' ' '); do
	test -d $dir/$s || continue
	cp -R $dir/$s/* $tmp
	setup_copied=yes
	modmaster $s
done
if test "$setup_copied" != "yes" && test -d $dir/default; then
	cp -R $dir/default/* $tmp
	modmaster default
fi

f=$GOPATH/bin/calicoctl
mkdir -p $tmp/bin
test -x $f && cp $f $tmp/bin

cd $tmp
tar cf "$1" *
cd - > /dev/null
rm -rf $tmp
