#! /bin/sh

dir=$(dirname $0); dir=$(readlink -f $dir)
tmp=/tmp/xcluster_$$
die() {
    echo "ERROR: $*" >&2
    rm -rf $tmp
    exit 1
}
log() {
    echo "$*" >&2
}
test -n "$1" || die "No out-file"

#test -n "$KUBERNETESD" || die 'Not set [$KUBERNETESD]'
#test -d "$KUBERNETESD" || die "Not a directory [$KUBERNETESD]"

# Allow both v1.10.13 and v1.10
sdir=$dir/$__k8sver
if ! test -d $sdir; then
	sdir=$(echo $sdir | sed -E 's,\.[0-9]+$,,')
	test -d $sdir || die "Not a directory [$sdir]"
fi
mkdir -p $tmp/bin
cp -R $sdir/* $tmp

# Copy cri-o
d=$GOPATH/src/github.com/cri-o/cri-o/bin
test -d $d || die "Not a directory [$d]"
cp $d/* $tmp/bin

# Install libraries
$XCLUSTER cplib --dest=$tmp $tmp/bin/*

cd $tmp
tar cf "$1" *
cd - > /dev/null
rm -rf $tmp
