#! /bin/sh
# NOTE: A common pattern is to specify "-" (stdout) as out-file,
#  so there must be NO log printouts to stdout!

dir=$(dirname $0); dir=$(readlink -f $dir)
tmp=/tmp/$USER/xcluster_$$
die() {
	echo "ERROR: $*" >&2
	rm -rf $tmp
	exit 1
}
log() {
	echo "INFO: $*" >&2
}

test -n "$1" || die "No out-file"

mkdir -p $tmp
for s in $(echo "$SETUP" | tr ',' ' '); do
	test -d $dir/$s || continue
	cp -R $dir/$s/* $tmp
	setup_copied=yes
done
test "$setup_copied" != "yes" && test -d $dir/default && cp -R $dir/default/* $tmp
test -n "$K3S_TEST" && cp -R $dir/$K3S_TEST/* $tmp

find_util() {
	local d
	for d in "$GOPATH/src/github.com/rancher/k3s/dist/artifacts" \
		"$ARCHIVE" "$GOPATH/bin" "$(dirname $XCLUSTER)/bin/$1"; do
		if test -x "$d/$1"; then
			echo "$d/$1"
			return 0
		fi
	done
	which "$1"
}

eval $($XCLUSTER env | grep ARCHIVE)
mkdir -p $tmp/bin
for f in k3s coredns mconnect; do
	x=$(find_util $f)
	test -n "$x" || die "Not found [$f]"
	cp $x $tmp/bin
done
$XCLUSTER install_prog --dest=$tmp jq

# Flannel does not support ipv6 so install bridge CNI-plugin;
if echo "$SETUP" | grep -q ipv6; then
	d=$GOPATH/src/github.com/containernetworking/plugins/bin
	mkdir -p $tmp/opt/cni/bin
	for n in bridge host-local loopback; do
		test -x $d/$n || die "Not executable [$d/$n]"
		cp $d/$n $tmp/opt/cni/bin
	done
fi

# Certificates are required for image pull
mkdir -p $tmp/etc/ssl/certs
cp /etc/ssl/certs/ca-certificates.crt $tmp/etc/ssl/certs/

cd $tmp
tar cf "$1" *
cd - > /dev/null
rm -rf $tmp
