#! /bin/sh
# NOTE: A common pattern is to specify "-" (stdout) as out-file,
#  so there must be NO log printouts to stdout!

dir=$(dirname $0); dir=$(readlink -f $dir)
tmp=/tmp/$USER/xcluster_$$
die() {
	echo "ERROR: $*" >&2
	rm -rf $tmp
	exit 1
}
log() {
	echo "INFO: $*" >&2
}

test -n "$1" || die "No out-file"
out=$1
shift

$dir/cni-plugins.sh archive > /dev/null || die "Missing archive"

mkdir -p $tmp/opt/cni/bin
$dir/cni-plugins.sh install --dest=$tmp/opt/cni/bin $@ || die

test "$CNI_PLUGIN_TEST" = "yes" && cp -R $dir/test/* $tmp

cd $tmp
tar cf "$out" *
cd - > /dev/null
rm -rf $tmp
