#! /bin/sh
# NOTE: A common pattern is to specify "-" (stdout) as out-file,
#  so there must be NO log printouts to stdout!

dir=$(dirname $0); dir=$(readlink -f $dir)
tmp=/tmp/$USER/xcluster_$$
die() {
	echo "ERROR: $*" >&2
	rm -rf $tmp
	exit 1
}
log() {
	echo "INFO: $*" >&2
}

test -n "$1" || die "No out-file"
mkdir -p $tmp/bin

test -n "$__criover" || __criover=crio-v1.22.0
ar=$__criover.tar.gz
test -r $ARCHIVE/$ar || die "Not readable [$ARCHIVE/$ar]"
log "Using cri-o binary release $__criover"
tar -C $tmp --strip-components=1 -xf $ARCHIVE/$ar cri-o/bin

if test "$CRIO_LOCAL" = "yes"; then
	log "Using local built cri-o"
	criod=$GOPATH/src/github.com/cri-o/cri-o
	for n in crio pinns crio-status; do
		f=$criod/bin/$n
		test -x $f || die "Not executable [$f]"
		cp $f $tmp/bin
	done
fi

# (until we have some hooks...)
mkdir -p $tmp/usr/share/containers/oci/hooks.d

test -d $dir/default && cp -r $dir/default/* $tmp

$XCLUSTER cplib --dest=$tmp $tmp/bin/*

cd $tmp
tar cf "$1" *
cd - > /dev/null
rm -rf $tmp
