#! /bin/sh
# NOTE: A common pattern is to specify "-" (stdout) as out-file,
#  so there must be NO log printouts to stdout!

dir=$(dirname $0); dir=$(readlink -f $dir)
tmp=/tmp/$USER/xcluster_$$
die() {
	echo "ERROR: $*" >&2
	rm -rf $tmp
	exit 1
}
log() {
	echo "INFO: $*" >&2
}

test -n "$1" || die "No out-file"

mkdir -p $tmp/bin
criod=$GOPATH/src/github.com/cri-o/cri-o
for n in crio pinns crio-status; do
	f=$criod/bin/$n
	test -x $f || die "Not executable [$f]"
	cp $f $tmp/bin
done

f=$ARCHIVE/runc.amd64
test -x $f || die "Not executable [$f]"
cp $f $tmp/bin/runc

f=$GOPATH/src/github.com/containers/conmon/bin/conmon
test -x $f || die "Not executable [$f]"
cp $f $tmp/bin
ver=v1.16.1
ar=$ARCHIVE/crictl-$ver-linux-amd64.tar.gz
test -r $ar || die "Not readable [$ar]"
tar -C $tmp/bin -xf $ar

# (until we have some hooks...)
mkdir -p $tmp/usr/share/containers/oci/hooks.d

test -d $dir/default && cp -r $dir/default/* $tmp

$XCLUSTER cplib --dest=$tmp $tmp/bin/*

cd $tmp
tar cf "$1" *
cd - > /dev/null
rm -rf $tmp
