#! /bin/sh
# NOTE: A common pattern is to specify "-" (stdout) as out-file,
#  so there must be NO log printouts to stdout!

dir=$(dirname $0); dir=$(readlink -f $dir)
tmp=/tmp/$USER/xcluster_$$
die() {
	echo "ERROR: $*" >&2
	rm -rf $tmp
	exit 1
}
log() {
	echo "INFO: $*" >&2
}

test -n "$1" || die "No out-file"

mkdir -p $tmp
cp -R $dir/default/* $tmp

$XCLUSTER install_prog --dest=$tmp ping tracepath jq curl ethtool

mkdir -p $tmp/bin
f=$GOPATH/src/github.com/Nordix/mconnect/image/mconnect
if test -x $f; then
	cp $f $tmp/bin
else
	f=$ARCHIVE/mconnect-v2.0.gz
	test -r $f || die "Not readable [$f]"
	zcat $f > $tmp/bin/mconnect
	chmod a+x $tmp/bin/mconnect
fi

f=$XCLUSTER_WORKSPACE/pmtud/pmtud
if test -x $f; then
   $XCLUSTER install_prog --dest=$tmp $f
else
   log "Not executable [$f]"
fi

cd $tmp
tar cf "$1" *
cd - > /dev/null
rm -rf $tmp
