#! /bin/sh
# NOTE: A common pattern is to specify "-" (stdout) as out-file,
#  so there must be NO log printouts to stdout!

dir=$(dirname $0); dir=$(readlink -f $dir)
tmp=/tmp/$USER/xcluster_$$
die() {
	echo "ERROR: $*" >&2
	rm -rf $tmp
	exit 1
}
log() {
	echo "INFO: $*" >&2
}

test -n "$1" || die "No out-file"

mkdir -p $tmp
cp -R $dir/default/* $tmp

eval $($XCLUSTER env | grep -E '^KERNELDIR|__kver')
kdir=$KERNELDIR/$__kver

# install bpftool
f=$kdir/tools/bpf/bpftool/bpftool
test -x $f || die "Not executable [$f]"
$XCLUSTER install_prog --dest=$tmp $f

# install libbpf
f=$kdir/tools/lib/bpf/root/*
cp -R $f $tmp/

# install perf
f=$kdir/tools/perf/perf
test -x $f || die "Not executable [$f]"
$XCLUSTER install_prog --dest=$tmp $f

# install xdptest (kernel+userspace) programs
mkdir -p $tmp/root/xdptest
make -C src O=$tmp/root/xdptest > /dev/null || die "Build"

# install xdp-tools examples
d=$XCLUSTER_WORKSPACE/sys/usr/local/sbin
$XCLUSTER install_prog --dest=$tmp $d/xdp-loader
$XCLUSTER install_prog --dest=$tmp $d/xdp-filter
$XCLUSTER install_prog --dest=$tmp $d/xdpdump

d=$XCLUSTER_WORKSPACE/sys/usr/local/lib/bpf
mkdir -p $tmp/usr/local/lib/bpf
cp -R $d $tmp/usr/local/lib

# install AF_XDP bpf-examples
d=$GOPATH/src/github.com/xdp-project/bpf-examples

for x in AF_XDP-example AF_XDP-forwarding; do
	mkdir -p $tmp/root/$x
	for n in xdpsock xdpsock_kern.o xsk_fwd; do
		f=$d/$x/$n
		test -r $f && cp $f $tmp/root/$x
	done
done

cd $tmp
tar cf "$1" *
cd - > /dev/null
rm -rf $tmp
