apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kpng-lb-proxier
spec:
  selector:
    matchLabels:
      app: kpng-lb-proxier
  template:
    metadata:
      labels:
        app: kpng-lb-proxier
    spec:
      hostNetwork: true
      containers:
      - name: kpng
        image: registry.nordix.org/cloud-native/kpng-lb-proxier:latest
        securityContext:
          privileged: true
