#! /bin/sh
# NOTE: A common pattern is to specify "-" (stdout) as out-file,
#  so there must be NO log printouts to stdout!

dir=$(dirname $0); dir=$(readlink -f $dir)
tmp=/tmp/$USER/xcluster_$$
die() {
	echo "ERROR: $*" >&2
	rm -rf $tmp
	exit 1
}
log() {
	echo "INFO: $*" >&2
}

test -n "$1" || die "No out-file"

# Get the address to the local registry
regip=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' registry) \
	|| die "Can't get address of the local registry"
test -n "$regip" || die 'Address empty'

# Check the port
docker inspect registry | jq '.[]|.NetworkSettings.Ports' | grep -q '5000/tcp' ||\
	die "Non standard port (!=5000) used for the local registry"
regip="$regip:5000"
#log "Address [$regip]"

mkdir -p $tmp
cp -R $dir/default/* $tmp
sed -i -e "s,%localreg%,$regip," $tmp/var/lib/rancher/k3s/agent/etc/containerd/config.toml.tmpl

if test -n "$__dns_spoof"; then
	test -r "$__dns_spoof" || die "Not readable [$__dns_spoof]"
	dip=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.Gateway}}{{end}}' registry)
	for n in $(cat $__dns_spoof); do
		echo "$dip $n" >> $tmp/etc/hosts
	done
fi

cd $tmp
tar cf "$1" *
cd - > /dev/null
rm -rf $tmp
