apiVersion: v1
kind: Service
metadata:
  name: mserver
spec:
  ipFamilyPolicy: RequireDualStack
  selector:
    app: mserver
  type: LoadBalancer
  ports:
  - port: 5001
    name: mconnect
  - port: 5003
    name: ctraffic
  - port: 80
    name: http
  - port: 8080
    name: kahttp
  - port: 8443
    name: kahttps
---
apiVersion: v1
kind: Service
metadata:
  name: mserver-udp
spec:
  ipFamilyPolicy: RequireDualStack
  selector:
    app: mserver
  type: LoadBalancer
  ports:
  - port: 5001
    protocol: UDP
    name: mconnect
  - port: 5003
    name: ctraffic
    protocol: UDP
