apiVersion: v1
kind: Service
metadata:
  name: mconnect-ipv4
spec:
  ipFamilies:
    - IPv4
  selector:
    app: mconnect
  ports:
  - port: 5001
    name: mconnect
  type: LoadBalancer
  loadBalancerIP: "10.0.0.1"
---
apiVersion: v1
kind: Service
metadata:
  name: mconnect-ipv6
spec:
  ipFamilies:
    - IPv6
  selector:
    app: mconnect
  ports:
  - port: 5001
    name: mconnect
  type: LoadBalancer
  loadBalancerIP: "1000::1"
---
apiVersion: v1
kind: Service
metadata:
  name: mconnect-preferdual
spec:
  ipFamilyPolicy: PreferDualStack
  selector:
    app: mconnect
  ports:
  - port: 5001
    name: mconnect
  type: LoadBalancer
