#! /bin/sh
cat > /etc/resolv.conf <<EOF
nameserver fd00:4000::2
options use-vc
EOF
. /etc/profile
if test "$(hostname)" = "vm-002"; then
	while ! kubectl apply -f /etc/kubernetes/coredns.yaml; do
		sleep 2
	done
fi

while ! kubectl get endpoints coredns > /dev/null 2>&1; do
	sleep 1
done

pat='.subsets[].addresses[].ip'
ept=$(kubectl get endpoints coredns -o json | jq -r "$pat")
while test -z "$ept"; do
	sleep 1
	ept=$(kubectl get endpoints coredns -o json | jq -r "$pat")
done

rm -f /etc/resolv.conf
for n in $ept; do
	echo "nameserver $n" >> /etc/resolv.conf
done
echo "options use-vc"  >> /etc/resolv.conf
