#! /bin/sh
# NOTE: A common pattern is to specify "-" (stdout) as out-file,
#  so there must be NO log printouts to stdout!

dir=$(dirname $0); dir=$(readlink -f $dir)
tmp=/tmp/$USER/xcluster_$$
die() {
	echo "ERROR: $*" >&2
	rm -rf $tmp
	exit 1
}
log() {
	echo "INFO: $*" >&2
}

test -n "$1" || die "No out-file"

echo "$SETUP" | grep -q ipv4 || die "Weave only supports ipv4"

f=$ARCHIVE/cni-plugins-linux-amd64-v0.8.2.tgz
test -r $f || die "Not readable [$f]"
mkdir -p $tmp/opt/cni/bin
tar -O -xf $f ./portmap > $tmp/opt/cni/bin/portmap
chmod a+x $tmp/opt/cni/bin/portmap

cp -R $dir/ipv4/* $tmp

cd $tmp
tar cf "$1" *
cd - > /dev/null
rm -rf $tmp
