#! /bin/sh

dir=$(dirname $0); dir=$(readlink -f $dir)
tmp=/tmp/$USER/xcluster_$$
die() {
    echo "ERROR: $*" >&2
    rm -rf $tmp
    exit 1
}
log() {
    echo "INFO: $*" >&2
}

test -n "$1" || die "No out-file"

prg=$XCLUSTER_WORKSPACE/bin/coredns
test -x $prg || prg=$GOPATH/bin/coredns
test -x $prg || prg=$(dirname $XCLUSTER)/bin/coredns
test -x $prg || die "Not executable [$prg]"

mkdir -p $tmp/bin $tmp/etc
cp $prg $tmp/bin
cp $(dirname $XCLUSTER)/config/Corefile $tmp/etc


cd $tmp
tar cf "$1" *
cd - > /dev/null
rm -rf $tmp
