#! /bin/sh
# NOTE: A common pattern is to specify "-" (stdout) as out-file,
#  so there must be NO log printouts to stdout!

dir=$(dirname $0); dir=$(readlink -f $dir)
tmp=/tmp/$USER/xcluster_$$
die() {
	echo "ERROR: $*" >&2
	rm -rf $tmp
	exit 1
}
log() {
	echo "INFO: $*" >&2
}

test -n "$1" || die "No out-file"

findar() {
	ar=$ARCHIVE/$1
	test -r $ar && return 0
	ar=$HOME/Downloads/$1
	test -r $ar || die "Not readable [$ar]"
}

mkdir -p $tmp
cp -R $dir/default/* $tmp

$XCLUSTER install_prog --base-libs=/dev/null --dest=$tmp \
	wget ping tracepath hping3

findar mconnect.xz
xzcat $ar > $tmp/bin/mconnect
chmod a+x $tmp/bin/mconnect

findar ctraffic.gz
zcat $ar > $tmp/bin/ctraffic
chmod a+x $tmp/bin/ctraffic

findar kahttp.xz
xzcat $ar > $tmp/bin/kahttp
chmod a+x $tmp/bin/kahttp

for n in ctraffic mconnect kahttp; do
	f=$GOPATH/src/github.com/Nordix/$n/image/$n
	test -x $f || continue
	cp $f $tmp/bin
done
d=$GOPATH/src/github.com/Nordix/kahttp
test -d $d || die "Not a directory [$d]"
mkdir -p $tmp/etc
cp -r $d/image/etc/cert $tmp/etc

for n in ctraffic mconnect kahttp; do
	echo "$n:$($tmp/bin/$n -version)" >&2
done


cd $tmp
tar cf "$1" *
cd - > /dev/null
rm -rf $tmp
