apiVersion: v1
kind: Service
metadata:
  name: ctraffic
spec:
  selector:
    app: ctraffic
  ports:
  - port: 5003
  externalIPs:
  - 10.0.0.2
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ctraffic-deployment
spec:
  selector:
    matchLabels:
      app: ctraffic
  strategy:
    rollingUpdate:
      maxSurge: 0%
      maxUnavailable: 25%
    type: RollingUpdate
  replicas: 4
  template:
    metadata:
      labels:
        app: ctraffic
    spec:
      containers:
      - name: ctraffic
        image: nordixorg/ctraffic:v0.2
        ports:
        - containerPort: 5003
