apiVersion: v1
kind: Service
metadata:
  name: mserver-http-ipv4
spec:
  externalTrafficPolicy: Local
  ipFamily: IPv4
  selector:
    app: mserver-daemonset
  ports:
  - port: 80
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: mserver-http-ipv6
spec:
  externalTrafficPolicy: Local
  ipFamily: IPv6
  selector:
    app: mserver-daemonset
  ports:
  - port: 80
  type: LoadBalancer
