apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mserver-daemonset
spec:
  selector:
    matchLabels:
      app: mserver-daemonset
  template:
    metadata:
      labels:
        app: mserver-daemonset
    spec:
      serviceAccount: default
      containers:
      - name: mserver
        image: registry.nordix.org/cloud-native/mserver:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /pod-init
            name: pod-init
      volumes:
        - name: pod-init
          configMap:
            name: mserver-init
---
apiVersion: v1
kind: Service
metadata:
  name: mserver-daemonset
spec:
  selector:
    app: mserver-daemonset
  ports:
  - port: 5001
  type: LoadBalancer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mserver-init
data:
  pod-init: |
    echo "Turn off offload"
    ethtool -K eth0 gro off gso off tso off


