apiVersion: v1
kind: Service
metadata:
  name: mserver-mconnect-ipv4
spec:
  externalTrafficPolicy: Local
  ipFamily: IPv4
  selector:
    app: mserver-daemonset
  ports:
  - port: 5001
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: mserver-mconnect-ipv6
spec:
  externalTrafficPolicy: Local
  ipFamily: IPv6
  selector:
    app: mserver-daemonset
  ports:
  - port: 5001
  type: LoadBalancer
