#! /bin/sh
# NOTE: A common pattern is to specify "-" (stdout) as out-file,
#  so there must be NO log printouts to stdout!

dir=$(dirname $0); dir=$(readlink -f $dir)
tmp=/tmp/$USER/xcluster_$$
die() {
	echo "ERROR: $*" >&2
	rm -rf $tmp
	exit 1
}
log() {
	echo "INFO: $*" >&2
}

test -n "$1" || die "No out-file"

mkdir -p $tmp
for s in $(echo "$SETUP" | tr ',' ' '); do
	test -d $dir/$s || continue
	cp -R $dir/$s/* $tmp
	setup_copied=yes
done
test "$setup_copied" != "yes" && cp -R $dir/default/* $tmp

mkdir -p $tmp/bin
d=$GOPATH/src/github.com/cloudnativelabs/kube-router
for f in kube-router gobgp; do
	test -x $d/$f || die "Not executable [$d/$f]"
	cp $d/$f $tmp/bin
done

cd $tmp
tar cf "$1" *
cd - > /dev/null
rm -rf $tmp
