apiVersion: v1
kind: Service
metadata:
  name: mconnect-daemonset
spec:
  selector:
    app: mconnect-daemonset
  ports:
  - port: 5001
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: mconnect-daemonset-udp
spec:
  selector:
    app: mconnect-daemonset
  ports:
  - name: udp
    port: 5001
    protocol: UDP
  type: LoadBalancer
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mconnect-daemonset
spec:
  selector:
    matchLabels:
      app: mconnect-daemonset
  template:
    metadata:
      labels:
        app: mconnect-daemonset
    spec:
      containers:
      - name: mconnect
        image: nordixorg/mconnect:v1.2
        ports:
        - containerPort: 5001
