apiVersion: v1
kind: Service
metadata:
  name: mconnect
spec:
  selector:
    app: mconnect
  ports:
  - port: 5001
  type: NodePort
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mconnect-deployment
spec:
  selector:
    matchLabels:
      app: mconnect
  replicas: 4
  template:
    metadata:
      labels:
        app: mconnect
    spec:
      containers:
      - name: mconnect
        image: docker.io/nordixorg/mconnect:0.2
        ports:
        - containerPort: 5001
