apiVersion: v1
kind: Service
metadata:
  name: mconnect-daemonset-ipv4
spec:
  ipFamily: IPv4
  selector:
    app: mconnect-daemonset
  ports:
  - port: 5001
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: mconnect-daemonset-ipv6
spec:
  ipFamily: IPv6
  selector:
    app: mconnect-daemonset
  ports:
  - port: 5001
  type: LoadBalancer
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mconnect-daemonset
spec:
  selector:
    matchLabels:
      app: mconnect-daemonset
  template:
    metadata:
      labels:
        app: mconnect-daemonset
    spec:
      containers:
      - name: mconnect
        image: registry.nordix.org/cloud-native/mconnect:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5001
