#! /bin/sh
# NOTE: A common pattern is to specify "-" (stdout) as out-file,
#  so there must be NO log printouts to stdout!

dir=$(dirname $0); dir=$(readlink -f $dir)
tmp=/tmp/$USER/xcluster_$$
die() {
	echo "ERROR: $*" >&2
	rm -rf $tmp
	exit 1
}
log() {
	echo "INFO: $*" >&2
}

test -n "$1" || die "No out-file"

# Get the address to the local registry
regip=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' registry) \
	|| die "Can't get address of the local registry"
test -n "$regip" || die 'Address empty'
#log "Address [$regip]"

mkdir -p $tmp
for s in $(echo "$SETUP" | tr ',' ' '); do
	test -d $dir/$s || continue
	cp -R $dir/$s/* $tmp
	setup_copied=yes
done
test "$setup_copied" != "yes" && test -d $dir/default && cp -R $dir/default/* $tmp

sed -ie "s,%localreg%,$regip," $tmp/etc/crio/crio.conf
echo "192.168.0.250 example.com" >> $tmp/etc/hosts

cd $tmp
tar cf "$1" *
cd - > /dev/null
rm -rf $tmp
