#! /bin/sh
# NOTE: A common pattern is to specify "-" (stdout) as out-file,
#  so there must be NO log printouts to stdout!

dir=$(dirname $0); dir=$(readlink -f $dir)
tmp=/tmp/$USER/xcluster_$$
die() {
	echo "ERROR: $*" >&2
	rm -rf $tmp
	exit 1
}
log() {
	echo "INFO: $*" >&2
}

test -n "$1" || die "No out-file"

mkdir -p $tmp
cp -R $dir/default/* $tmp

images=$($XCLUSTER ovld images)/images.sh
dip=$($images lreg_ip)

sed -i -e "s,%localreg%,$dip," $tmp/etc/init.d/28private-reg.rc
echo "$dip example.com" >> $tmp/etc/spoofed-hosts
if test -n "$__dns_spoof"; then
	test -r "$__dns_spoof" || die "Not readable [$__dns_spoof]"
	for n in $(cat $__dns_spoof); do
		echo "$dip $n" >> $tmp/etc/spoofed-hosts
	done
fi

cd $tmp
tar cf "$1" *
cd - > /dev/null
rm -rf $tmp
