#! /bin/sh

export __nrouters=2
export __nets_vm=0,1,3,4,5
export __mem201=128
export __mem202=128
export __smp202=3
export __nets202=0,1,2,3,4,5
export __smp1=3
export __smp2=3
export __smp3=3
export __smp4=3
export __smp5=3
export __smp6=3
export __smp7=3
export __smp8=3

if ip netns id | grep -q _xcluster; then
	# Ensure bridges for net 3-4
	for i in 3 4 5; do
		if ! ip link show xcbr$i > /dev/null 2>&1; then
			$XCLUSTER br_setup $i || echo "ERROR: could not create xcbr$i"
		fi
	done
fi
