#! /bin/sh
# NOTE: A common pattern is to specify "-" (stdout) as out-file,
#  so there must be NO log printouts to stdout!

dir=$(dirname $0); dir=$(readlink -f $dir)
tmp=/tmp/$USER/xcluster_$$
die() {
	echo "ERROR: $*" >&2
	rm -rf $tmp
	exit 1
}
log() {
	echo "INFO: $*" >&2
}

mkdir -p $tmp
test -n "$1" || die "No out-file"

progs="make lscpu realpath jq"
$XCLUSTER install_prog --dest=$tmp $progs || die "kselftest dependencies not installed"

eval $($XCLUSTER env | grep -E '^KERNELDIR|__kver')
kdir=$KERNELDIR/$__kver
log "Including kselftest"
mkdir -p $tmp/kernel
KSFT_INSTALL_PATH=$tmp/kernel make -C $kdir/tools/testing/selftests install > /dev/null 2>&1 || die "kselftest not installed"

cd $tmp
tar cf "$1" *
cd - > /dev/null
rm -rf $tmp
