#! /bin/sh

dir=$(dirname $0); dir=$(readlink -f $dir)
tmp=/tmp/xcluster_$$
die() {
    echo "ERROR: $*" >&2
    rm -rf $tmp
    exit 1
}
log() {
    echo "$*" >&2
}
test -n "$1" || die "No out-file"

mkdir -p $tmp/bin $tmp/sbin
for s in $(echo "$SETUP" | tr ',' ' '); do
	test -d $dir/$s || continue
	cp -R $dir/$s/* $tmp
	cd $tmp
	tar cf "$1" *
	cd - > /dev/null
	rm -rf $tmp
	return
done

cp -R $dir/default/* $tmp

# Some binaries can't be replaced by BusyBox applets
f=/bin/kmod
test -x $f || die "Not executable [$f]"
cp $f $tmp/sbin/modprobe
f=/usr/bin/find
test -x $f || die "Not executable [$f]"
cp $f $tmp/bin/find

test -n "$KUBERNETESD" || KUBERNETESD=$GOPATH/src/k8s.io/kubernetes/_output/bin
test -d "$KUBERNETESD" || die "Not a directory [$KUBERNETESD]"
for n in kube-controller-manager kube-scheduler kube-apiserver \
	kube-proxy kubectl kubelet; do
	test -x $KUBERNETESD/$n || die "Not executable [$KUBERNETESD/$n]"
	cp $KUBERNETESD/$n $tmp/bin
	strip $tmp/bin/$n
done

# Certificates are required for image pull
mkdir -p $tmp/etc/ssl/certs
cp /etc/ssl/certs/ca-certificates.crt $tmp/etc/ssl/certs/

$XCLUSTER install_prog --dest=$tmp jq base64

f=$GOPATH/src/github.com/Nordix/assign-lb-ip/assign-lb-ip
test -x $f || f=$GOPATH/bin/assign-lb-ip
test -x $f && cp $f $tmp/bin

# Install libraries
$XCLUSTER cplib --dest=$tmp $tmp/bin/*

cd $tmp
tar cf "$1" *
cd - > /dev/null
rm -rf $tmp
