apiVersion: v1
kind: Service
metadata:
  name: mconnect-no-proxy
  labels:
    service.kubernetes.io/service-proxy-name: none
spec:
  selector:
    app: mconnect
  ports:
  - port: 5001
    name: mconnect
