apiVersion: v1
kind: Service
metadata:
  name: mconnect
spec:
  selector:
    app: mconnect
  ports:
  - port: 5001
  externalIPs:
  - 10.0.0.2
---
apiVersion: v1
kind: Service
metadata:
  name: mconnect-udp
spec:
  selector:
    app: mconnect
  ports:
  - name: udp
    port: 5001
    protocol: UDP
  externalIPs:
  - 10.0.0.2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mconnect-deployment
spec:
  selector:
    matchLabels:
      app: mconnect
  replicas: 4
  template:
    metadata:
      labels:
        app: mconnect
    spec:
      containers:
      - name: mconnect
        image: nordixorg/mconnect:v1.2
        ports:
        - containerPort: 5001
