apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-deployment
spec:
  selector:
    matchLabels:
      app: alpine
  replicas: 4
  template:
    metadata:
      labels:
        app: alpine
    spec:
      containers:
      - name: alpine
        image: library/alpine:latest
        imagePullPolicy: IfNotPresent
        command: ["sh", "-f", "/pod-init/pod-init"]
        env:
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        volumeMounts:
          - mountPath: /pod-init
            name: pod-init
      volumes:
        - name: pod-init
          configMap:
            name: pod-init
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pod-init
data:
  pod-init: |
    echo "Starting POD $(hostname) on $MY_NODE_NAME"
    nc -lk -p 5001 -e hostname
