#! /bin/sh

export USRSCTP_TOPOLOGY=nat
export __nvm=2
export __nrouters=2
export __ntesters=2
export __nets_vm=0,1,2
export __nets201=0,1,3
export __nets202=0,2,4
export __nets221=0,3,4
export __nets222=0,3,4
export __mem201=128
export __mem202=128

if ip netns id | grep -q _xcluster; then
	# Ensure bridges for net 3-4
	for i in 3 4; do
		if ! ip link show xcbr$i > /dev/null 2>&1; then
			$XCLUSTER br_setup $i || echo "ERROR: could not create xcbr$i"
		fi
	done
fi
